### ISSUE TITLE
BassShaker "lSimulated Road Texture, Gear, Missed Gear play only on Right audio Channel

### ISSUE THREAD

**Issue by LennartSolik** [SHWotever/SimHub#1002]
**Describe the bug**
The effects:
Simulated Road Texture
Gear Shift
Missed Gear

only play on right audio Channel and it doesn't matter if you choose Mono, left/right, front/back, or custom channels in audio output. In the effects tab there is also no left right drop-down menu and only one graph with the test now button is showing. 
If the games don't support left right for these effects please fix it so that these effects play at least on all shakers (audio channels)

**Simhub version**
7.4.16

**To Reproduce**
connect audio device (nobsound mini USB)
Configure sound output (mono, left/right, front/back)
Go to effects profile 
(Simulated road texture, gear shift, missed gear)
Press Test on graph
Bass only plays on right audio Channel 
(Disconnect right speakers and you will hear nothing)

**Expected behavior**
Effects need drop-down menu für right/left side otherwise play effect on all speakers (simulated road texture NEEDs left/right support if this is possible since the kerb effects are most noticable with this effect and would be amazing in a left/right shaker assembly)

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by SHWotever** [comment]
Hi !

All these effects are per nature "mono" so they spread to all the channels identically, that's why there is no selector to reduce the number of channels it's generating. But overall all these effects are powerful (because they are made to trigger a big impact) if you can't feel them on the left channel I would suspect that the amplifier is shutting down. Could you try with headphones to check that both channels are working independently of the amplifier ?
