### ISSUE TITLE
No display on my Vocore dash display.

### ISSUE THREAD

**Issue by lauriegrant13** [SHWotever/SimHub#1024]
I have installed a new Vocore display and on my gaming PC once it is setup and connected on simhub the display stays black. I also set the LED's up and they work fine. When I go into device manager USB2.0 screen shows up.
I then attached the screen to my laptop that also has simhub and the display works fine but back on the gaming PC nothing. I then down loaded  Dashpanel to see if it would work on that on the gaming PC and that worked fine.
I have updated all drivers on the gaming PC as well. I then completely uninstalled simhub and reinstalled with and earlier version to see if that worked but it did not so I am back to version 7.4.21.

[SimHub.log](https://github.com/SHWotever/SimHub/files/8082651/SimHub.log)

![IMG_1384](https://user-images.githubusercontent.com/99257525/154335217-622a0246-57ba-488b-b3ab-e45152e7a0a3.jpg)
![IMG_1385](https://user-images.githubusercontent.com/99257525/154335236-37a9efc7-e259-4401-aa7b-636950d72952.JPG)
![IMG_1379](https://user-images.githubusercontent.com/99257525/154335241-1f35e423-8559-4e09-ae36-b8c801cca977.jpg)
![IMG_1380](https://user-images.githubusercontent.com/99257525/154335257-edc6d519-86c5-43eb-8f0c-81c2779d7843.jpg)
![IMG_1381](https://user-images.githubusercontent.com/99257525/154335273-0e81cf38-c1f7-4456-9b3c-1dd6ecb5289c.jpg)
![IMG_1382](https://user-images.githubusercontent.com/99257525/154335292-f982f4c0-6fc9-4008-98fe-62d2cd5ddde5.jpg)
![IMG_1383](https://user-images.githubusercontent.com/99257525/154335312-3a768aef-0e82-49b3-819e-76a364f9ef6b.jpg)

**Comment by SHWotever** [comment]
Hi !

Thanks for the log, by reading it it seems there is nothing obvious occuring, So I fear it will require to proceed by elimination

As a first test could you try to display the following url (when simhub is running)  http://127.0.0.1:8888/Dash#McLaren+720s+gt3|nocontrols|usbd480 in any browser (ideally chrome) ? That would help to know if the issue is occuring in the internal server running the dash.

If the screen appears black too could you send me the template so I can check ? Does another template works ?

I see that the device comes with leds too which are not driven by DashPanel, could you try to disable the leds inside simhub (disable arduino in the arduino tab) to see if somehow it interacts with the screen (lack of power ...) .

When the screen connects (after disabling it for a time the rehabbing it) do you see the simhub logo ? 

Nicolas

**Comment by lauriegrant13** [comment]
Thanks for the quick reply Nicolas.

So in chrome it says this page isn't working.

No other templates work either.

With arduino disabled the screen is still black.

When reconnected there is no simhub logo

**Comment by SHWotever** [comment]
Thanks for the feedback that allows to reduce the scope to the server itself.

Sorry for this new question list ;) 

- Do you you have a specific error message when you try to load the page in the browser ? Like ERR_CONNECTION_REFUSED ?

- Can you access the web dash list using http://127.0.0.1:8888/ ? 

- If you can't access it I would check that the firewall/antivirus is not blocking simhub ? Could you try to disable temporary your firewall/and or antivirus ?
- I've also already seen recently issues with VPN software blocking "PC to PC" communications, do you use some vpn software ?

- Another possibility is that another software is already using the port. Can you try to change it in simhub settings (it will require a simhub restart) : 
![image](https://user-images.githubusercontent.com/2207331/154346329-1aa42cb9-96b1-4a4d-bc18-448ff3de4aa7.png)

**Comment by lauriegrant13** [comment]
I will try all this tomorrow.

**Comment by lauriegrant13** [comment]
So what do I change  port number to? Never done that before

**Comment by SHWotever** [comment]
You can change the port to any port at your will, you can use the same 10555 port as I used in my screenshot for instance.

**Comment by lauriegrant13** [comment]
it seems that changing the port number has worked. I now have a dash that works. Thankyou Nicolas you have been a great help

**Comment by SHWotever** [comment]
Perfect ! Thanks for your feedback !
