### ISSUE TITLE
Malware detected

### ISSUE THREAD

**Issue by CrashalotMark** [SHWotever/SimHub#1029]
**Describe the bug**

**Simhub version**
Make sure to run the latest version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**
I downloaded simhub for my button box on my PC & have had problems with the software from day 1. So l ran security program it it detected malware on simhub. This nearly broke my PC though luckily l deleted simhub before it done anymore damage. Please could remove the malware from simhub so the program can be used for everyone without it breaking data. Thanks

**Comment by SHWotever** [comment]
Hi ! Simhub is checked with the most common antiviruses however some of them (like avast or norton) sometimes triggers false positives . Do not hesitate to report the false positive to your antivirus vendor so they can fix it : https://github.com/SHWotever/SimHub/wiki/SimHub-Troubleshootings#simhubexe-disappears-or-antivirus-detects-simhub

**Comment by CrashalotMark** [comment]
Malware detected. The malware was detected through totalav antivirus & when using simhub the PC would slow down when using gaming ports.

**Comment by SHWotever** [comment]
Hi ! Concerning the malware, do you have a name ? I double checked the files (windows defender, and an enterprise grade AV) with no detection. But like I said some antiviruses will detect simhub based on behaviors, or simply after a new version because it's not yet used by enough users (that kind of false positives is occuring often on Norton, I don't know if TotalAV uses the same kind of "usage reputation" algorythm). Often heuristic detection will contain a ! (exclamation mark) in the name indicating that it's a detection based on heuristic instead of malware database.

Simhub (and lot of similar softwares) concentrates lot of various technologies (udp, tcp, memory reading, plugins etc ...) which can trigger some antiviruses false positive. Unfortunately as a small developper I can't fight those, and often they simply tends to stop detecting simhub after a few weeks after a new release (I released the lasst one only 12 days ago, time for the AV developers to white list the new version.    

If you are interested about the subject here is a very nice article describing the struggle of small developpers facing those false positives : https://weblog.west-wind.com/posts/2016/oct/05/dealing-with-antivirus-false-positives#anti-virus-hell  

Concerning the slow down do you have the log files so I can take a look ? Can you explain "when using gaming ports", i'm sorry I did not understood that sentence.

Nicolas
