### ISSUE TITLE
Malware file

### ISSUE THREAD

**Issue by CrashalotMark** [SHWotever/SimHub#1031]
**Describe the bug**

**Simhub version**
Make sure to run the latest version

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

**Additional context**

**Comment by CrashalotMark** [comment]
Hi I have found the malware file in Simhub 7.04.21 Through totalav & its a spyware in  called HEUR/APC

**Comment by SHWotever** [comment]
Hi ! I close this as duplicate ;) "HEUR" means it's an heuristic detection , I reported the false positive to totalav using their false positive report page. Unfortunately this can be only fixed by your antivirus provider. You can read my explanation about false positives and heuristics based detections here in your previous ticket here : https://github.com/SHWotever/SimHub/issues/1029#issuecomment-1048249627

Best regards,
Nicolas
