### ISSUE TITLE
[Feature request] Add force feedback telemetry for Richard Burns Rally

### ISSUE THREAD

**Issue by tobier** [SHWotever/SimHub#1041]
**Is your feature request related to a problem? Please describe.**
There is currently no property for the force feedback output in Richard Burns Rally.
It would be very convenient to have this supported for doing things like monitoring the FFB curve when tweaking settings.

**Describe the solution you'd like**
Add FFB as a property in Richard Burns Rally. There is a known memory address where the FFB is written, see the following example in Python:

```python
import atexit
import time

from rwmem import *


def main():
    memory.open('RichardBurnsRally_SSE.exe')
    atexit.register(memory.close, 'RichardBurnsRally_SSE.exe')

    ffb_pointer = memory.read(0x007eac48, TYPE="int") + 0xc04
    while True:
        try:
            time.sleep(0.2)
            ffb = memory.read(ffb_pointer, TYPE="float")
            print(ffb)
        except:
            pass


if __name__ == "__main__":
    main()
```
This can be run without any privilege escalation. I'm not sure if this is how telemetry is read right now (I only think NGP6 telemetry is over UDP?); if it's already something like the above it should be trivial to add this. 

**Describe alternatives you've considered**
This could probably be implemented as a plugin using the SDK, but then it might as well be a feature since it's just one new property.

**Additional context**
N/A

**Comment by SHWotever** [comment]
hi! 
Thanks for the insight ! I wasn't aware of this pointer. I've added the value in game rawdata for the next release.

Nicolas

**Comment by mika-n** [comment]
> @mika-n Currently the simhub udp version is a mix between memory reading and UDP so I get the best of both worlds ;)

Excellent. I thought about mentioning this some time ago, but never got around to suggest that it would be great to have a possibility to use both UDPTelemetry and dataReader offset variables at the same time to have both in one overlay/dashboard, especially because UDPTelemetry doesn't send any data during RBR replays (without doing special tricks to "replay" udp packets or using mem offsets to during replay to populate udp data packets), but dataReader offsets used by the Default mode are available also during replay. But you were already ahead of this, nice...
