### ISSUE TITLE
[Feature request] - "Import dashboard" button and double clicking .xxprofile files

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#1059]
**Is your feature request related to a problem? Please describe.**
Hi,
The difference in how dash vs leds/shaker profiles are imported can be slightly confusing.
I see new comers sometimes ask on Discord  how to import dashboards.

**Describe the solution you'd like**
It would be nice to have an "Import dashboard" button in the dash (and overlay?) list.
On the other hand it could also be handy (and for consistency sake) to be able to import the .xxprofile files by double clicking them.

Bon week end!

**Comment by SHWotever** [comment]
Hello ! I've added the import dashboard to the next beta version.

Concerning xxprofile (leds ...) since it has many dynamic targets (usb devices, arduino, nextion  ....)  it's not possible to have a simple "doubleclick" import action, it would simplify the major use case(arduino leds) but on another end it would be confusing for other devices :(

**Comment by Romainrob** [comment]
Hi,
I missed the mail, but I noticed the button ;)
Thank you for the addition!
Bonne journée.
