### ISSUE TITLE
Still a little problem with Fuel_RemainingLaps data

### ISSUE THREAD

**Issue by fralbo** [SHWotever/SimHub#1097]
SimHub 8.0.1

Hello, data are much better managed in 8.0.1 but I noticed a remaining problem with `Fuel_RemainingLaps` data.
As you can see below, it's not possible to realize 9 laps with 25 L and 2.87 L per lap.

![Dash!](https://i.imgur.com/sb3BM7v.png)

Maybe just a rounding problem...

We can notice a little difference between ACC's L/lap and simhub's L/lap, also a rounding difference maybe...

Best regards,
Alain

**Comment by SHWotever** [comment]
Hi ! Value is valid, 25/2.87=8.71, rounded it gives 9. If you want to ignore the decimal part you can use truncate function : truncate (value) it will remove the decimal part instead of rounding

**Comment by fralbo** [comment]
No sorry! If you run 8.71 lap, you do not execute 9 lap except if you push the car up to the pit!
So, ok we can use truncate to fix it

**Comment by SHWotever** [comment]
Hi in fact there is a strict separation between the computed data which is giving full decimal precision and display which mathematically uses mid point rounding. unless using explicit truncate it will use this common standard rounding and this behaviour can't vary depending of the input data, that's why the only way is to use truncate.
