### ISSUE TITLE
simlab sd43 usdb480 screen flickering above 20 fps

### ISSUE THREAD

**Issue by gocsik83** [SHWotever/SimHub#1134]
**Describe the bug**
The screen constantly flickers on 60,50,40,30 fps on my simlab sd43 usdb480 screen.Only works without issue on 20 fps. My motherboard is msi 570s tomhawk. 20 fps is too slow for me, how can i use this with 60 fps without flickering?
**Simhub version**
8.0.4

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/9229510/SimHub.log)

**Comment by SHWotever** [comment]
Hi !

Flickering on the usbd480 is always caused by an usb bandwidth issue. Make sure you are not using an usb hub as it can cause such issues. If you are already taking a proper usb port from the motherboard try to change ports often there is a single usb root which is shared by multiple ports (and so bandwidth is shared too) . There could be also some usb drivers issues even if it's way more rare. 

Nicolas

**Comment by gocsik83** [comment]
Dear Nicolas,

I would like to thank you very much for your help, I rearranged the connection of the usb cables and the problem was solved!

**Comment by SHWotever** [comment]
Perfect thanks for your feedback!
