### ISSUE TITLE
Brake temp for AC dont compute Braketemps for all wheels

### ISSUE THREAD

**Issue by Doprintityourself** [SHWotever/SimHub#1158]
**Describe the bug**
available Attributes for AC are not filled with data values of the AC all 4 Brake Temps stay on 26°C
Atributes 
GameData.BrakeTemperatureFrontLeft
GameData.BrakeTemperatureFrontRight
GameData.BrakeTemperatureRearLeft
GameData.BrakeTemperatureRearRight

do not work either for RGB LEDs with Arduino
nor in Dashboard with Tire and Brake Temperature Template

**Simhub version**
Make sure to run the latest version

**To Reproduce**
1. Go to available properties
2. Start Game
3. Drive and watch realtime Values
4. See Brake temps not changing stay at 26

**Expected behavior**

**Screenshots**
![grafik](https://user-images.githubusercontent.com/70262325/192715313-77727103-7aa5-4ecd-b294-2e39e48331e1.png)
![grafik](https://user-images.githubusercontent.com/70262325/192719882-5c7f70ae-e1db-41c2-860a-dce5e9cfcbd0.png)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
[SimHub.log](https://github.com/SHWotever/SimHub/files/9662655/SimHub.log)

**Additional context**
tested with 8.1.1
With 3 different Cars of AC BMW Z4 GT3 , Lambo und Audi LMS

**Comment by SHWotever** [comment]
Hi !

I checked, indeed some cars does not reports any changes about temperature, I tested  BMW Z4 GT3 which is frozen. On some other cars like the aventador it works. From my understanding it depends of the car model since telemetry channels are not dependent of the car. It's quite common also that some telemetry channels are not given to telemetry (it happens a lot on rf2 for instance) not sure if it's the case for those cars in AC.

Nicolas
