### ISSUE TITLE
Simhub forgets Shakers Audio output and resets all routing settings

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1165]
Simhub randomly (= can't reproduce on purpose but it happens once a week) forgets the audio output for the bass shakers. it is disabled in Simhub, when turning back on, it is reset to default routing.

**Comment by SHWotever** [comment]
Hi !

This happens when the drivers get reinstalled. It seems that there is some windows update acting regularly and reinstalling the whole device. You can recover the old settings by checking "show disconnected" on bottom of the simhub output list.

Unfortunately the matching can't be done by name because there can be multiple time the same sound card, so it has to be by windows output unique Id

**Comment by FullPace** [comment]
Thanks for the excplanation. The settings transfer option works fine 👍
