### ISSUE TITLE
SimHub randomly crashes

### ISSUE THREAD

**Issue by 820fahrer** [SHWotever/SimHub#1191]
**Describe the bug**
SimHub is randomly crashing.

I made a clean install a few days ago and at the moment I have no idea what's happening.

Sometimes I can reproduce the issue when switching from my desk screen to the sim rig.
A few minutes ago it immediately crashed after opening it from the minimized taskbar icon.

Sometimes it crashed when I'm ingame. I use SimHub for my bass shakers. So while im in a race it suddenly stops.
Unfortunately I accepted this yesterday and didn't note the time, so no log file for this..

**Simhub version**
8.1.3

**Log files**
[SimHub.txt](https://github.com/SHWotever/SimHub/files/10189359/SimHub.txt)

If there is something missing please tell me.

**Comment by SHWotever** [comment]
Hi !

Unfortunately without the appropriate log, that will be hard to figure what happened, could you submit me the related log after it happens ?

Nicolas

**Comment by 820fahrer** [comment]
Hi

thanks for your quick reply.
Later today I will do some testing to reproduce the issues again. I will 
post the logs again.

The already posted log file is from yesterday. It's the log file when 
SimHub crashed after being opened from the taskbar.
I just had clicked in the opened window and it crashed.

Am 09.12.2022 11:07 schrieb Wotever:

**Comment by SHWotever** [comment]
Hi ! Thanks for your feedback, by reading the logs, I could not find a crash pattern, it was showing a full session from 19:05 to 21:03, with no specific ending, the only suspicious thing i could find was a crash from VRS_DirectForce_Pro_Wheel_Base being unavailable (maybe just powered off).

In case the logs show nothing after a crash, it can sometimes happen when the cause is external (not up to date overlay system, some software can also try to inject into apps)
In this case there should be some events in the windows event viewer :

Errors often comes by pair when a .net application crashes (my example shows a random application crash just for the illustration) :
![image](https://user-images.githubusercontent.com/2207331/206698128-ae20f90e-6f40-4043-9328-3e4e7a61259d.png)

**Comment by 820fahrer** [comment]
Hi

I just tried to reproduce the issue. It was no problem to let SimHub Crash after switching from the main monitor on the desk to the other on the rig.

As in the first log there is nothing suspicious: 
[simhub.txt](https://github.com/SHWotever/SimHub/files/10196888/simhub.txt)

I found two errors in the event viewer:

> Name der fehlerhaften Anwendung: SimHubWPF.exe, Version: 1.0.0.0, Zeitstempel: 0x636654e7
Name des fehlerhaften Moduls: amdxn32.dll, Version: 8.14.10.209, Zeitstempel: 0x63580615
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0006816d
ID des fehlerhaften Prozesses: 0x31f8
Startzeit der fehlerhaften Anwendung: 0x01d90bf51fcd48de
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\SimHub\SimHubWPF.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\DriverStore\FileRepository\u0385333.inf_amd64_939a9895acbd8403\B384893\amdxn32.dll
Berichtskennung: aae84b59-0173-459a-8e17-42652ade3d4a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

> Anwendung: SimHubWPF.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0000005, Ausnahmeadresse 5B06816D
Stapel:

As I can see it's something with the AMD drivers I guess.
I found some problems with DirectX9 and the mentioned file.

My graphics driver: Adrenaline 22.10.3

Maybe important: CPU Ryzen 3600XT, GPU RX 6900 XT

**Comment by SHWotever** [comment]
Hi !

This is indeed a low level crash with graphics drivers and WPF d3d9. Looking at the graphics driver version it seems that's it up to date, so I would maybe think at some windows update not applied ? Windows 10.0.19044 is 21H2 if i'm not wrong, but there is a latest version 22H2 since november. I hope it could improve the WPF compatibility with those fresh drivers. Simhub is using .net WPF. I did not had similar report yet, so I hope it's just an windows/drivers update combo not behaving correctly.

Nicolas

**Comment by 820fahrer** [comment]
> Hi !
> 
> This is indeed a low level crash with graphics drivers and WPF d3d9. Looking at the graphics driver version it seems that's it up to date, so I would maybe think at some windows update not applied ? Windows 10.0.19044 is 21H2 if i'm not wrong, but there is a latest version 22H2 since november. I hope it could improve the WPF compatibility with those fresh drivers. Simhub is using .net WPF. I did not had similar report yet, so I hope it's just an windows/drivers update combo not behaving correctly.
> 
> Nicolas

You were right, I used Windows version 21H2. 
Unfortunately the update to 22H2 didn't make a change.
It was easy to let simhub crash due to the monitor change. (Win+P and switch to the second screen).

I have no explanation but I will try to close Afterburner and Riva Statistics in the future, to test if there is a problem with SimHub and these applications.
