### ISSUE TITLE
[Feature request]Add Digital Combat Simulator and Falcon BMS

### ISSUE THREAD

**Issue by dureiken** [SHWotever/SimHub#1201]
Hi

would it be possible to add plane game which already have telemetry ? I thought about digital combat simulator (DCS) and Falcon BMS ?

Thanks a lot :)

**Comment by SHWotever** [comment]
Hi !
Currently I don't plan to add any flight sims, it's a really specific domain,  adding flight sims is not impossible but I fear it to be incomplete due to my lack of knowledge about flight sims. 
I know that some features like fans or bass shakers are less demanding about it, but simhub contains many more features and I don't want a "poor" support for flight sims.
