### ISSUE TITLE
Opening telemetry .json files

### ISSUE THREAD

**Issue by ilBegno** [SHWotever/SimHub#1236]
Hi, I guess this is more of a help request rather than a feature request, I'm trying to figure out if there's a way to look at the telemetry.json data recordings outside of the replay viewer.

Unfortunately when I try to open the json file with notepad++ I only see random characters (wrong encoding?)
I was expecting to perhaps see variables like speed, engine rpm, tyre temps logged over time, so that I could process them with my own python scripts or other programs.

Is there any solution to this? 
Thanks in advance for your help!

**Comment by SHWotever** [comment]
Hi !

No it's not possible, it's a compressed half binary half json file mixed with pictures and record index. It's also storing "unprocessed raw game data" so you wouldn't find a consistent structure across games in all cases. This file serves both the replay feature and a troubleshooting feature where a record gives back the game raw data and allows to process it again to fix some data interpretation issues if any. Due to this content it's also not possible to add a "conversion" to normalized telemetry, there would be too much data to process to do it in a decent time. 

I plan to add a real telemetry recording in the future, but it won't be mixed with the replays. As you might have seen replays are quite big files and it's not something which is viable to store telemetry for long durations.

Nicolas

**Comment by ilBegno** [comment]
Ah okay, yeah it would be great to have a real telemetry recording feature which offers a standardized set of datapoints across all supported games, but I understand that it's probably a pretty big ask considering all the games that simhub supports.

Anyway, thank you very much for answering, have a nice day!
