### ISSUE TITLE
Unexpected behavior: zero AttachDelegate() property values after ReadCommonSettings() until values are set again

### ISSUE THREAD

**Issue by blekenbleu** [SHWotever/SimHub#1240]
**Describe the bug**
value[] array values are correctly recovered by ReadCommonSettings(),
but zero is reported for those property values after AttachDelegate()
until after e.g. value[i] = value[i];

**Simhub version**
8.2.2

**To Reproduce**
1. AttachDelegate() some non-zero value
2. view its value reported in "Available properties"
3. set value = value
4. view correct property value

**Expected behavior**
I expected current property value to be displayed after AttachDelegate()

**Additional context**
work around at line 746
https://github.com/blekenbleu/blekenbleu.MIDIio/blob/main/IOproperties.cs

**Comment by SHWotever** [comment]
Hi !

Attach delegate does evaluate delegates after each values reads.I've not read the whole code as it was a full project not reduced at the issue example, but take care of variable captures, that's probably your issue here : it's not simhub specific but a .net framework features regarding anonymous delegates : http://www.digitallycreated.net/Blog/34/variable-capture-in-c%23-with-anonymous-delegates

**Comment by SHWotever** [comment]
A little tip when you are troubleshooting anonoymous, 
You can put a breakpoint specifically on the anonymous content by putting your cursor in the anonymous code and pressing F9. This will put your breakpoint in the exact anonymous code and allow you to watch it. You will be able to see the exact code being executed and local variables (including captures) and see what you got wrong.

**Comment by blekenbleu** [comment]
Unable to duplicate unexpected behavior in a simple example
https://github.com/blekenbleu/Unexpected
