### ISSUE TITLE
Ambient Light Bluetooth connects but can't control light

### ISSUE THREAD

**Issue by selectabo** [SHWotever/SimHub#1247]
**Describe the bug**
I'm trying to set up ambient lighting plugin using a bluetooth LED strip compatible with Happy Lighting App and Bluetooth 5.0 Adapter. The Ambient Light plugin connects to the LED strip but in the interface shows with a Red strip that sometimes flickers to Green. I can't control the lights.

**Simhub version**
V 8.2.3

**To Reproduce**
1. Connect lights
2. Add new device
3. Click OK when device shows up

**Expected behavior**
LED Strip device shows up in Devices box with green strip and able to control lights

**Screenshots**

![image](https://user-images.githubusercontent.com/113193310/224506638-60a64228-cce7-4bd9-9c4c-9be9c5a9023a.png)
![image](https://user-images.githubusercontent.com/113193310/224506700-33888585-a7c9-4065-a7ff-532411aead51.png)

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/10949218/SimHub.log)

**Comment by SHWotever** [comment]
Hi !

I took a look at the logs, the update areas error could sometimes happen after resolution /screen mode changes etc but it's only temporary.

I feel the issue is more about the lights connectivity. Could you make sure that your lighs are not paired on the computer itself or on any devices ? This blocks the BLE connectivity. Just having the original app left running on your phone could be enough to mess ip. 

Do you have the exact model of those lights ? In theory if you could add them it's that the bluetooth signature matches a supported device but maybe it has some additionnal constraints.

**Comment by selectabo** [comment]
Thanks.

It's these lights.

Bluetooth LED Strip 5M Waterproof LED Strips Lights Music Sync Color
Changing RGB 12V 5050 Cuttable Sticky LED Lights with Remote&App Control
Lights for Bedroom Outdoor Party TV Kitchen https://amzn.eu/d/eNyyjnt

I tried it with my phone turned off and the lights aren't paired with the
computer still the same behaviour.

**Comment by SHWotever** [comment]
Thnaks for the information, currently I've tested mostly flood lights as shown in the documentation : https://github.com/SHWotever/SimHub/wiki/Ambient-lights#bluetooth-lights

I'm wondering if those long strips are capable of holding the high refresh rate of simhub and are just simply disconnecting when beeing "flooded". Unfortunately these lights are not avaialble from France, I will try to get one "I don't know how yet" :D

As a side option I will release very soon govee support which uses the official api and not reverse engeneering like ble lights is using. This should get a much more previsible support and offer "known to work" lights.

**Comment by selectabo** [comment]
Yeah. I struggled to get a floodlight that worked with happy lighting here
so took a risk on the led strip.

Looks like a no go. Thanks for looking at it.
