### ISSUE TITLE
[BUG] Control Mapper ABS not working

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1248]
I have assigned two wheels to  ABS+ and ABS- in the control mapper with vJoy as the output device.
When assigned the controls via the smarthphone helper website, ABS + and ABS - are not working. I can see the wheels triggering the right commands in control mapper (buttons turning red) but the web app doesn't seem to send anything.

TC and Turbo worked fine though.

**Comment by SHWotever** [comment]
Hi !

I double checked everything went fine, orignally i was fearing some issues with special characters (+/-) when trigerred from the web ui, but everything is protected here.

Can you check that the inputs are trigerred in the windows control panel ?
![image](https://user-images.githubusercontent.com/2207331/225906827-b5fd1d3a-c332-4860-a003-5de86f4f5156.png)

That would allow to know if the issue is in simhub or in the game. In the meanwhile i've changed a little the delay used by the web assistant to set it to 200ms, if somehow the game needs a longer press.

**Comment by FullPace** [comment]
Hi, I just tested and the ABS Buttons are not recongized by vjoy as you can see on this screenshot (both abs buttons are pressed and recognized by simhub but not in game controller)
![oJFDzaRUJa](https://user-images.githubusercontent.com/116221480/226141581-f169b7d0-1837-4820-84a7-d319bd1334ff.png)

**Comment by SHWotever** [comment]
Hi ! It looked OKs like your vjoy is limited to only 8 buttons, can you make sure you have 128 as shown in the documentation? https://github.com/SHWotever/SimHub/wiki/Control-Mapper-plugin#vjoy

**Comment by FullPace** [comment]
my bad, i set it up as 128 buttons but somehow it switched back to 8 buttons and I didn‘t pay attention. setting it again to 128 fixed it. thank you

**Comment by SHWotever** [comment]
I added some alerts about this configuration in the next version, since vjoy default is 8 buttons from memory better warn about it directly when it's not correctly configured.
