### ISSUE TITLE
Wind Simulator not working in ACC Multiplayer

### ISSUE THREAD

**Issue by xexets** [SHWotever/SimHub#1249]
**Describe the bug**
In ACC in multiplayer only wind simulation (Speed) works only for the first lap and then stops working. Works fine in single player ACC and in any other game. When wind sim stops working in MP shake it motors and bass shakers continue to work absolutely fine.
Note that when windsim stops working if, while ACC is still running, I jump to SimHub and turn on idle wind, it still does not work in ACC MP. If I assign a button to turn on/off Speed wind and/or Idle wind, it does nothing in ACC but as soon as I exit ACC if Idle wind is on the fans spin up!

**Simhub version**
8.2.3 but happened on previous versions too
Wind sim is on an Arduino One, configured as PWM

**To Reproduce**
With wind sim configured in simhub and working fine open ACC, join a multiplayer server, run a couple of laps.

**Expected behavior**

Win sim should continue to work

**Screenshots**
N/A

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs

[Logs.zip](https://github.com/SHWotever/SimHub/files/10999869/Logs.zip)

**Additional context**

**Comment by SHWotever** [comment]
Hi thanks for the report, I think I already fixed it for the next version, the issue was some ghost players in multiplayer session with no proper coordinates breaking the draft effect computations, can you try with draft mode disabled to confirm this is the same issue ? 
![image](https://user-images.githubusercontent.com/2207331/225872147-b6cffc2e-0394-4280-a509-96d67d372706.png)

**Comment by xexets** [comment]
That's amazing, many thanks! I'll try it later today or early next week as
I am leaving in the afternoon and will report back asap. Thank you so much
for this!

**Comment by xexets** [comment]
that was it many thanks! works fine without draft enabled. thank you!
