### ISSUE TITLE
OpenHardwareMonitor

### ISSUE THREAD

**Issue by RodentYell** [SHWotever/SimHub#1266]
Installing 8.3.3 I have noticed being able to select 'OpenHardwareMonitor' under Settings/System Info/System Monitoring Configuration/Enabled providers, if I drop back to 8.2.3 all is good again.

**Comment by SHWotever** [comment]
Hi ! It's intentional, unfortunately open hardware monitor is not updated anymore and had some critical exploit which now makes it legitimately detected as a security threat by some advanced antivirus (https://github.com/openhardwaremonitor/openhardwaremonitor/issues/1560). Due to that I had to remove this component. However there is still various alternatives available free or not which are not affected by this issue: https://github.com/SHWotever/SimHub/wiki/System-informations

**Comment by RodentYell** [comment]
Disappointing, so we're getting rid of it because of AVG..Wont use the other providers not paying for something else.

**Comment by SHWotever** [comment]
Not specifically for avg, it was the first to detect it, but the security threat does not depend of the antivirus in the end. I've weighted for about a month if I should or not remove this component, knowing a threat and keeping it embedded in SimHub would not be a responsible behaviour from me overall. And even if I liked myself having a ready to use system info, I had to be reasonable and not expose everyone to this security threat. That's overall my responsibility. From experience security often deserve useability, there are compromise to be found, but the limit is not to expose users to known risks.

I'm fighting a lot with antivirus false positives, but to my eye this one is legitimate as it exposes users to a danger ... unlinke the numerous false positives I've been facing since 7 years which never made me remove a feature.

**Comment by b3nz0** [comment]
Hi @SHWotever - why is this driver still present in my system if was removed in 2023?

`WinRing0_1_2_0	WinRing0_1_2_0: WinRing0	(Verified) Noriyuki MIYAZAKI	C:\Program Files (x86)\SimHub\OpenHardwareMonitorLib.sys	Thu Apr 13 13:19:47 2023	`

Can I simply delete this file without any impact to SimHub? is there a reason why subsequent SimHub upgrades didnt remove this component?
