### ISSUE TITLE
SystemInfosProvider

### ISSUE THREAD

**Issue by RipperGOT** [SHWotever/SimHub#1284]
Since I updated to 8.3, [SystemInfosProvider.MainCPUFanSpeed] [NULL] stopped working. 
I use it to monitor the percentage of RPM of the fan, as sometimes it doesn't start properly. 

Am I mistaken that the only way to obtain a reading of the percentage is with OpenHardwareMonitor? 
Is there any other way to read the CPU fan revolutions percentage?

**Comment by SHWotever** [comment]
Hi ! It's intentional, unfortunately open hardware monitor is not updated anymore and had some critical exploit which now makes it legitimately detected as a security threat by some advanced antivirus (openhardwaremonitor/openhardwaremonitor#1560). Due to that I had to remove this component. However there is still various alternatives available free or not which are not affected by this issue: https://github.com/SHWotever/SimHub/wiki/System-informations
