### ISSUE TITLE
Delay when using udp telemetry to bass shaker 

### ISSUE THREAD

**Issue by Dad4boys13** [SHWotever/SimHub#1308]
Noticeable lag between game input and bass shaker effect. Using a Dayton BST1 bass shaker, Aiyama A07 amp, ugreen usb sound card, pc to ps5 on f122. Half a second delay.

**Comment by SHWotever** [comment]
Hello! That's huge indeed, are you using a wired network? Maybe it's a bit overloaded? If somehow your network is overloaded as counterintuitive it may look you can try to reduce the UDP frequency in the game settings so it gets lighter. How your amplifier is wired ? I see it's a Bluetooth compatible one, but Bluetooth can sometimes involves huge latency. Make sure to use wires instead of Bluetooth to eliminate this possibility.

**Comment by SHWotever** [comment]
Hum, have you tried another sound card? Maybe straight from the computer output. Usb dongles usually works well, but it's worth eliminating this clue too.

**Comment by Dad4boys13** [comment]
Tried another sound card, same issue. I can also assure you the network is
not overloaded. Amp is not bluetooth. Tried reducing UDP t0 30 instead of
60, nothing...lol
