### ISSUE TITLE
[UPDATE] Simucube Wheel disconnect

### ISSUE THREAD

**Issue by FullPace** [SHWotever/SimHub#1323]
Hey,
remember the issue with disconnecting wheel bases?
I think I finally found what is going on and I'm sure now it wasn't a Simhub issue.

After updating to the latest Simhub version last week the problem came back.
I crashed in game.  I heared usb disconnect and the wheel was dead.

Beacause I reinstalled vjoy  about the same time I investigated some more and now I can nail it down to  vjoy.
It seems like whenever I crash my usb cable of the wheel gets a little lose through the tension and disconnects.
I assume vjoy re-orders or re-loads all usb devices in the background which causes 
the wheelbase to disconnect in the game.

I could reproduce it by switchting wheels in game without quitting before.

I uninstalled vjoy and the problem was gone.

Just wanted to let you know.

Have a good one

**Comment by SHWotever** [comment]
Hi ! 

Thanks for the feedback ! That's really strange indeed, I did locate a FFB issue triggered by Simhub which had be fixed since, but I did not see any linked to vjoy in particular (I use it on all my machines) 

That said there might be some "race conditions" here depending of the whole setup, hard to tell. As an alternative if you want to use the control mapper the arduino based adapter will avoid you such struggles, as Vjoy is a low level driver I have no power here :D

**Comment by FullPace** [comment]
I just wanted to let you know so you don’t have to invest more time.

I‘ll stick with Joy2Key for now.

Do you plan to enhance functionality? It could really benefit from multiple fn keys (double functions for encoders) and long press / short press actions 😁

**Comment by FullPace** [comment]
sounds like a great roadmap!
