### ISSUE TITLE
Support AC on PlayStation

### ISSUE THREAD

**Issue by DeineMutter1983** [SHWotever/SimHub#1328]
Hello, 
I use SimHub for Dashboard and Shakelt Motors with NLR HF8 on the PS4. I know PlayStation is not the main focus in SimHub, but I still have a request. Is it possible to connect Assetto Corsa to the Playstation in SimHub in the Future? I'm asking because I have a dashboard app that works with AC and PlayStation. That means that AC gives out telemetry data! In the App you have to put in the IP-Adress of Playstation like GT Sport and GT7 in SimHub.

**Comment by SHWotever** [comment]
Hi ! There is some kind of telemetry given for AC on PS4 but it's extremely basic, I prefer not to add it, as you pointed I keep simhub focused on pc. And unlike GT for which I got many requests as soon as telemetry as been discovered you're actually the very first asking for the console version of AC after all those years. 

There is also an investment and maintenance side on this position, adding consoles in a general manner requires to buy all the consoles, games, store all of that for no real usage (I'm not a "console" person) and it adds all the testing required for all those platforms. Consoles are also more complicated to troubleshoot, network, routers, wifi, lot of additional things are added to the potential troubles. Since I'm alone behind the scenes it's a work load I can't add at this point.

**Comment by DeineMutter1983** [comment]
Okay, too bad! Most will play AC on PC because of the mods that do not run on console. But I'm still surprised that I'm the only one who asked for it. But I would still be happy if it might work at some point ;). Thanks for the quick reply!Von meinem iPhone gesendetAm 10.06.2023 um 18:12 schrieb Wotever ***@***.***>:﻿
Hi ! There is some kind of telemetry given for AC on PS4 but it's extremely basic, I prefer not to add it, as you pointed I keep simhub focused on pc. And unlike GT for which I got many requests as soon as telemetry as been discovered you're actually the very first asking for the console version of AC after all those years.
There is also an investment and maintenance side on this position, adding consoles in a general manner requires to buy all the consoles, games, store all of that for no real usage (I'm not a "console" person) and it adds all the testing required for all those platforms. Consoles are also more complicated to troubleshoot, network, routers, wifi, lot of additional things are added to the potential troubles. Since I'm alone behind the scenes it's a work load I can't add at this point.
