### ISSUE TITLE
OLED SCREEN drive Problem[Feature request]

### ISSUE THREAD

**Issue by xuezhe8973** [SHWotever/SimHub#1332]
My OLED use SH1106 driver which can not use the code you give directly, i tryed to write the code in CustomProtocol, the "class" and "private" stucked and even simhub said my hardware unrecognised, I use the U8G2 lib in arduino, that cause the fact but i dont have other way to solve [it]

**Comment by xuezhe8973** [comment]
![屏幕截图 2023-06-16 171600](https://github.com/SHWotever/SimHub/assets/67494816/b9b42720-04e9-4ad5-b2a6-6a3e2ff9a673)

**Comment by SHWotever** [comment]
Hi ! Unfortunately the oled screens requires lot of memory limiting extremely the possibilities due to this constrains. it not the kind of hardware I plan to push any further with more supported variations etc... We now have usb devices (ax206, vocore) which are working directly through usb, for a very moderate price.
