### ISSUE TITLE
[Feature request] Higher UDP rate support for F1 23

### ISSUE THREAD

**Issue by mantazzo** [SHWotever/SimHub#1338]
**Is your feature request related to a problem? Please describe.**
Currently, SimHub gives an error if you have anything else other than 60Hz selected. However, F1 23 now has new options available (100Hz and 120Hz), and SimHub gives an error that it's "not correctly configured" even though it does work.

**Describe the solution you'd like**
Allow anything over 60Hz rate. Any lower rate could get a "recommendation" that a better send rate is recommended.

**Describe alternatives you've considered**
None.

**Additional context**
Just wanted to offer a change to remove a somewhat unnecessary "not configured" notification when it is actually set correctly, since the game now supports even higher send rates.

**Comment by SHWotever** [comment]
Hi ! Simhub is locked to 60fps as a performance trade between game resources usage or SimHub CPU usage that's why it wants to configure the game accordingly. 

You can still configure it faster if needed and use the "ignore" button, it was the actual goal of it : if somehow you need a "non nominal" configuration (using an udp relay, changing the frequency ...) : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/012f343d-8fa5-44fd-9a7f-a7c57c151bf0)

Overall just for SimHub 60FPS is the best value, setting it to more will only raise the CPU usage to process wasted higher frequency data with no benefits since CPU consumption cumulates for every useless bits I think it's better to keep it suggest the most appropriate frequency. 

And raising the whole Simhub clock to match it would not be reasonable, switching from 60 to 120hz means doubling the consumption, it would be too much.

**Comment by mantazzo** [comment]
Fair enough. I can understand the reasoning behind this.

**Comment by mantazzo** [comment]
With that being said, I'm closing this as my question was answered.
