### ISSUE TITLE
diablo 4 LED support [Feature request]

### ISSUE THREAD

**Issue by chunterosa** [SHWotever/SimHub#1348]
**Is your feature request related to a problem? Please describe.**
no?

**Describe the solution you'd like**
I honestly have no idea what sort of code it uses or if it's even possible to create a plugin, but diablo 4 has led support and I'd like my arduino powered RPM leds to glow with my health levels, flash when low and any other data that might be fun to use?

**Describe alternatives you've considered**
signalRBG claims to have some sort of solution that should work with my alienware led but it was not worth the headache and expense to figure out. 

**Additional context**
i love you no matter what.  you have helped me up my sim racing setup to the nth degree and it's one of the best app purchases I've ever made.

**Comment by SHWotever** [comment]
Hi ! Thanks for your feedback. Even if a few "non racing" games made it's place in the past I now try to keep focused on racing games (and maybe flight sims in the future). The few "non racing" games I added are providing a deceptive feeling as there is not much out of box dashes/displays/effects compatible with it and that's why it feels worse adding them.

Concerning Diablo 4 specifically I've not seen any public api,  they might be using memory hooks which are not viable at large scale.

**Comment by chunterosa** [comment]
makes sense to me! thanks for the reply and explanation.  much appreciated.
