### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by kaaac** [SHWotever/SimHub#1358]
Is it possible to serve dashboards using https connection?

**Comment by SHWotever** [comment]
Hi ! No, HTTPS requires a domain name, while simhub is simply attached to a "no name" TCP http endpoint.

To get full https you need to add an "intermediate"  : IIS reverse proxy aka ARR, apache, or any reverse proxy supporting HTTPS.
Warning : Simhub is excuslively designed for internal network access, exposing it to the whole internet (which is required for getting a valid HTTPS certificate) would expose you to unmesured risks,

**Comment by kaaac** [comment]
Thanks for your reply!

Currently trying to configure proxy for simhub, using traefik solution (with proper secure authorization).
Almost everything works ok, but after dash load there is issue with websocket content through https (mixed content). 
So, finally dashboard not working :(.
My thoughs was maybe it would be possible to add domain name and certificate directly to simhub.

Did you tried to serve dashboards through any proxy?

**Comment by SHWotever** [comment]
No I never tried in the simhub contect, I'm sorry, as it's really not designed for public exposure (I'm used to reverse proxy through IIS using ARR otherwise), but I don't know anything about traefik .The safest way would be a secure VPN access, but it's even more complex to get it configured than a reverse proxy.

For science (I overinsist about security risks ;) ). 
Overall to avoid the mixed content issues I think using the WSS protocol in cc.js would do the trick : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/2982d085-8677-404b-91f2-204a11da5ed2)

NB : As you might understood ... except for science .. don't expose SimHub over internet ;) I can't decently help you much more getting your computer at risk ;).

**Comment by kaaac** [comment]
Exactly this part causes issue, for now. 

And for security im going to allow access from public after secure login :)
