### ISSUE TITLE
I'm not getting any sound from the shakers.

### ISSUE THREAD

**Issue by gr4474** [SHWotever/SimHub#1359]
**Describe the bug**
I reinstalled Simhub after a year or so of a break from sims. I have the paid license. I am not getting anything from the shakers. I have Windows 10 updated. I tried multiple sound cards, amps and even new shaker pucks I had. I have googled and found several people with the exact issues, and tried everything mentioned. I see .net Framework 4.8 Runtime is needed, and was having trouble going back to that version. I finally have both .NET Framework 3.5 (includes .NET 2.0 and 3.0) and .NET Framework 4.8 Advanced Services. I tried disabling .NET Framework 3.5.  I uninstalled Simhub fully, and deleted all files, and reinstalled. Nothing is working.  To me the shakers are a huge part of sim racing, and I really need help to get this working. Should I reinstall Windows?  That is going to be horrible after setting up Assetto Corsa, and Content Manager ect over the past week, but all that is depending on Simhub.
Please help. I really appreciate it!

**Simhub version**  8.4.5
Make sure to run the latest version

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

**Additional context**
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/11925222/SimHub.2.txt)
[SimHub.PackageManager.Standalone.1.log](https://github.com/SHWotever/SimHub/files/11925223/SimHub.PackageManager.Standalone.1.log)
[SimHub.PackageManager.Standalone.2.log](https://github.com/SHWotever/SimHub/files/11925224/SimHub.PackageManager.Standalone.2.log)
[SimHub.PackageManager.Standalone.3.log](https://github.com/SHWotever/SimHub/files/11925225/SimHub.PackageManager.Standalone.3.log)
[SimHub.txt](https://github.com/SHWotever/SimHub/files/11925226/SimHub.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/11925227/SimHub.1.txt)

**Comment by SHWotever** [comment]
Hi !

Out of the box all effects are disabled to avoid the "shaking mess" , are you sure to have some of the effects enabled ? Can you make sure that the output is not muted neither ?
![image](https://github.com/SHWotever/SimHub/assets/2207331/670d71b4-7742-414d-93ef-b1887fd644cf)

Usually when there is sound issues it's due to generic windows drivers being installed instead of the manufacturer ones, but the variety of sound card you are mentionning makes me think it's not the issue here. 

Just as a quick test does clicking on "test" inside the sound output gives something ? You should see the interface switching to "connected" in the header as well as some activity in the "vu meters", does it works and does it drives the shakers ?
![image](https://github.com/SHWotever/SimHub/assets/2207331/6c173f3a-52e0-459c-bd2d-5be04a30feae)

**Comment by gr4474** [comment]
I did get it working through the regular speakers. for some reason these pucks aren't working, even the new one. I'll keep trying with that. Thank you again.



________________________________
