### ISSUE TITLE
Simhub quicky disconnects and reconnects in iracing

### ISSUE THREAD

**Issue by JOAOMORETTO110711** [SHWotever/SimHub#1367]
**Describe the bug**when in iracing, during a race, my iflags (arduino) flashed very rapidly, and disconnected causing a quick stutter. then it connected back after 1sec
please see logs attached
[LapLog.txt](https://github.com/SHWotever/SimHub/files/11994583/LapLog.txt)
appreciate your help

**Comment by JOAOMORETTO110711** [comment]
Please help

**Comment by SHWotever** [comment]
Hi ! 

Usually such short disconnect is a consequence of the game freezing instead of the cause, 
If iracing stops updating telemetry for more than 2 seconds SimHub will consider the game as disconnected and reconnect as soon as data is live again. 

Could you join the simhub log file after it happens so I can check (simhub.txt in c:\Program Files (x86)\SimHub\logs)

**Comment by JOAOMORETTO110711** [comment]
hello, I will try to log again if it happens. but I think you nailed it. I had some freezes in iracing when it happened

**Comment by JOAOMORETTO110711** [comment]
Hello, had another issue just now. see the log attached please
[SimHub.txt](https://github.com/SHWotever/SimHub/files/12045630/SimHub.txt)

**Comment by SHWotever** [comment]
Hi ! Thanks for the log, I confirm that there were no other issues than the game stopping telemetry update. I can't see anything else sneaky happening.
