### ISSUE TITLE
White light only when using PL9823 and pro micro

### ISSUE THREAD

**Issue by kihyun9999** [SHWotever/SimHub#1375]
I'm building a ddu using a pl9823 and a promicro and vocore display. Made about 10 pieces.

While making a new ddu, when I connect the pl9823 to the promicro, only white light comes out from the pl9823.

I rechecked all the wiring and re-soldered all of them.
Also, I reset the simhub aduino tool by reusing 5 promicro, but all are the same.

I checked on 3 PCs and the version of the SimHub is the last version. The pro micro is an atmega32u4 5v. I am currently confused. It's so strange that something that was made well the day before doesn't work.

Is there anything else I can check?

We know that there is a fake issue of ch340g recently. Is there a problem with ATMEGA32U4?

Waiting for your reply. thank you

\**Describe the bug**

**Simhub version**
Make sure to run the latest version

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi white only on ws2812 (and pl) is most of the time due to reversed din and dout (basically feeding data via dout instead of din). You might also be victim of the "compatible" claims like lot of Chinese website shows and required timing maybe different. For instance at the time when I Implemented those LEDs they were claiming to be "ws2812 compatible" while the frequency required was not the same. Do you have the exact datasheet your your LEDs so I can check nothing is sneaky? Pin order or frequency might be different.

**Comment by kihyun9999** [comment]
![KakaoTalk_20230711_223107441](https://github.com/SHWotever/SimHub/assets/139892130/53855eec-b31c-480a-8007-aed92f10efb8)
![KakaoTalk_20230712_204312067](https://github.com/SHWotever/SimHub/assets/139892130/b0ac3474-f0ae-4ae9-b299-2d2581d02deb)
