### ISSUE TITLE
Iracing Led Spotter Car left/Right not working

### ISSUE THREAD

**Issue by jmaraquea** [SHWotever/SimHub#1395]
**Describe the bug**
In iRacing the Spotter Car Left/Right is not recognised, so the associated leds are not working accordingly.

Additionnally, I tried to use a spotter overlay (from the comunity) but the side detection is not working. The code is based in the following property DataCorePlugin.GameRawData.Telemetry.CarLeftRight and its value is permanently 1.

The voice spotter is working and states when a car is on your right or left.

**Simhub version**
8.4.11

**Third party plugins**
Enabled/Disabled

**Expected behavior**
When an in game car pass by your side the event should be triggered. The voice spotter is working.

**Log files**

[SimHub.7.txt](https://github.com/SHWotever/SimHub/files/12385877/SimHub.7.txt)
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/12385878/SimHub.1.txt)

**Comment by SHWotever** [comment]
Hi ! 

DataCorePlugin.GameRawData.Telemetry.CarLeftRight is the raw telemetry coming from the game without processing. If it's not changing it make sense that simhub can't illuminate the leds neither, I'm not sure if there are some conditions where the game would not report the spotter in telemetry, 1 means "clear" while 0 means off, since you have 1 it's showing that the spotter is indeed running, Maybe some server rules ? 

I checked in a simple mx5 with AI practice session the value is properly alive in my case : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/dae22b8d-530e-44c5-a571-fca5f4dae06c)

I will try to investigate, Iracing has lot of little kinks in telemetry like that, have you tried another car/series ? maybe it's not triggering in some conditions ?

**Comment by jmaraquea** [comment]
Yeah, I discovered was not triggering it under certain conditions which I'm not 100% sure but seems they are:

- End of the session.
- The game detecting you as no in driving conditions, e.g releasing the throttle for long in a straight to let them pass.
- The game detecting the other car not in driving conditions, e.g pit exit.

So I think the channel yes indeed is working fine and I just was not aware of the conditions of the channel.

Thank for your reply, if you get more information of the rules applied I would like to hear them!
