### ISSUE TITLE
Telemetary mark request

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#142]
Hi,

As requested on Discord. An idea is a telemetary mark option. If you have a problem press a button and it makes a little file somewhere with some important data at that point.

**Comment by SHWotever** [comment]
Hi ! I close it as it's now possible to add marks afterward in the replay.

**Comment by MorGuux** [comment]
Hi both :)

I still believe this could be implemented. Just a bindable event that when triggered (usually from a button press, but could be done from a dash or something), would place a marker on the replay that's being recorded, or possibly save the last "x" configurable seconds of a replay to a separate file (as a replay buffer style system, so the replays are not constantly recording and taking up disk space). Users could then leave the SimHub record feature permanently on while racing, without building up huge replay files.

Maybe some data properties made available to show the current number of markers triggered, time since the last marker, etc. for displaying a message in a dash when it is triggered.
