### ISSUE TITLE
The map in route advisor does not work

### ISSUE THREAD

**Issue by Albedorom** [SHWotever/SimHub#1432]
The map in the dashboard does not load.
Maybe I need to change the map URL somewhere, but I didn't find where. Please tell me how to solve the problem. I dealt with SIMHUB in fact only for the sake of route advisor, which does not work(((
![image](https://github.com/SHWotever/SimHub/assets/147193867/fdc6b78e-e4bd-4e4c-afc8-059523cb4a8f)
Thank you in advance for your help!

**Comment by SHWotever** [comment]
Hi ! 

Before being shown for the first time the map needs to be downloaded. I see on your screenshot that it is stuck to 0%.
Could you make sure your firewall is not blocking  simhub internet access? Alternatively are you using any VPN services which could slow down the download. If your re using a VPN could you try to disable it first ?

If that doesn't help could you fill the bug template as shown here so I can investigate further ? https://github.com/SHWotever/SimHub/issues/new?assignees=&labels=triage&projects=&template=bug_report.md&title=

**Comment by Albedorom** [comment]
Hi !
The firewall is checked, there are no locks. Just in case, I added simhub to the firewall exceptions, but the situation with the map is the same. I don't use a VPN.

**For playback**
Steps to reproduce the behavior:
1. Open SimHub - Truck Route Advisor
2. See the problem

**Expected behavior**
Downloaded map

**Screenshots**
The screenshot is attached above

**Log files**
Attached

Perhaps there is a way to upload the map to the dashboard as a file and not via the web ?

P.S.
Thanks for the quick response!!
[SimHub.1.txt](https://github.com/SHWotever/SimHub/files/12837169/SimHub.1.txt)
[SimHub.2.txt](https://github.com/SHWotever/SimHub/files/12837170/SimHub.2.txt)
[SimHub.3.txt](https://github.com/SHWotever/SimHub/files/12837171/SimHub.3.txt)
[SimHub.4.txt](https://github.com/SHWotever/SimHub/files/12837172/SimHub.4.txt)
[SimHub.5.txt](https://github.com/SHWotever/SimHub/files/12837173/SimHub.5.txt)
[SimHub.6.txt](https://github.com/SHWotever/SimHub/files/12837174/SimHub.6.txt)
[SimHub.7.txt](https://github.com/SHWotever/SimHub/files/12837175/SimHub.7.txt)
[SimHub.8.txt](https://github.com/SHWotever/SimHub/files/12837176/SimHub.8.txt)
[SimHub.9.txt](https://github.com/SHWotever/SimHub/files/12837177/SimHub.9.txt)
[SimHub.10.txt](https://github.com/SHWotever/SimHub/files/12837178/SimHub.10.txt)
[SimHub.txt](https://github.com/SHWotever/SimHub/files/12837179/SimHub.txt)

**Comment by SHWotever** [comment]
Thnaks !

After checking I noticed that game map switching was not working since the last update, here is a beta fixing it : https://www.simhubdash.com/unofficial/SimHub.9.01.2b1.zip

However in your your case there is still something blocking the map download, VPN, firewall, ISP maybe ? 
However you can download them directly here :
- ATS : https://simhubdash.com/TruckMaps/tsmap-ats.zip
- ETS : https://simhubdash.com/TruckMaps/tsmap-ets.zip

Simply close simhub and copy the zips without extracting them directly in the TruckMaps folder of simhub : C:\Program Files (x86)\SimHub\TruckMaps (if the folder does not exists simply create it first).

Nicolas
