### ISSUE TITLE
possible bug/issue com ports scanning

### ISSUE THREAD

**Issue by georgi-iovchev** [SHWotever/SimHub#1436]
Background info:
I noticed that when I use SimHub (and also after I exit it) my wireless headphones (Sony Inzone H9) are shown as disconnected in their software (Sony Inzone Hub). I tried to debug the problem and I found out that the reason is SimHub Arduino com port scanner. The wireless headset receiver is USB device, but it also is presented itself to windows as a com port (com3 in my case).
![image](https://github.com/SHWotever/SimHub/assets/23377650/1e309793-3505-41b2-9379-3817318514ba)

My current workaround is to use the SimHub option to "Never scan selected ports", or the other option "Scan only selected ports"
![image](https://github.com/SHWotever/SimHub/assets/23377650/a3571548-87b2-4ef9-bc8d-c361800e2b45)

I am not sure what happens programmatically during the com ports scan, but it has impact. I hope that this can be actually fixed on SimHub side, And then it will not be needed to include/exclude specific coms, because com port numbers may change when I rearrange or reconnect usbs.

I am attaching logs from Debug Mode with "Scan all serial ports" Arduino settings selected.
[SimHub.txt](https://github.com/SHWotever/SimHub/files/12851053/SimHub.txt)

**Comment by SHWotever** [comment]
Hi !

This limitation is valid in both directions, unfortunately all devices are not made equals to "unknown" data (surprising from sony I must admit). Nothing can be done here except filtering to the correct devices. 

Most of the cheap arduino clones uses CH340 which does not have a unique serial number and can change of allocated serial port number quite easily as you mentioned, that's why the scan and exclusion/inclusion list "exists" actually (that was not required on more "quality" usb to serial chips like FTDI ones, but a few years ago CH340 flooded the market). 

On quality devices you have a serial number associated allowing to keep consistent that allocated serial port and use safely the exclusion/inclusion list, that's the case of yours :
![image](https://github.com/SHWotever/SimHub/assets/2207331/69bed62c-ae7e-4f91-8d3f-8034709136bb)

If you want the safest solution make sure to use an official arduino or clone using an FTDI chip, this way you can work in full "inclusive" mode as serial ports are stable thanks to FTDI proper usb serial number implementation.

NB : "in an hypothetical world" The "hello" protocol used could be changed to avoid triggering the sony weaknesses, but there will be always one or another device not accepting it, not counting having to reflash all the arduino devices already existing to have this new protocol, it's a dead end on this side.

**Comment by georgi-iovchev** [comment]
Many thanks for your great explanation. It sounds perfectly reasonable and I accept it.
