### ISSUE TITLE
Simutec SDU-3 not always showing correct information

### ISSUE THREAD

**Issue by Brudrinker** [SHWotever/SimHub#1458]
**Describe the bug**

I will load ACC and initially the DDU may show the correct information. most of the time for a few minutes.  The it seems to have a delay from the SIM, in some cases i have counted 5 seconds between a gear change to the DDU updating.
Callum McGregor has also been in touch regarding this issue

**Simhub version**
Make sure to run the latest version

Report is from V.9.1.5.  I updated this morning to 9.108 and issues remain

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)

**To Reproduce**
Run ACC
Go on track. Issue occurs, maybe not straight away, but it does lose sync

**Expected behavior**

not to lose sync

**Screenshots**
I have provided the recording from the capture to Callum McGregor, I believe he has already sent this and another video through

**Log files**
[SimHub.8.txt](https://github.com/SHWotever/SimHub/files/13257195/SimHub.8.txt)

Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi !

Thanks for your log. 

I can see that the actual cause is not the sdu-3 but your mpx wheel which is "faulty" : the LEDs are quickly failing, reconnects correctly once then fails z last time and are not responding anymore, since it's mostly static colour LEDs this might not be obvious at first sight when in game. This causes simhub to "hang" while trying reconnect to the wheel LEDs again and again since it's not responding correctly. 
Can you try to disable the mpx to confirm it's the cause ?

In such case the cause is usually an usb issue (cable/hub) do not hesitate to contact grid so they can troubleshoot their hardware. 

Nicolas
