### ISSUE TITLE
Hue ambient light support

### ISSUE THREAD

**Issue by suppoo** [SHWotever/SimHub#1497]
**Is your feature request related to a problem? Please describe.**
I've recently obtained set of 2 Hue play bars and wondering if support is possible in simhub

**Describe the solution you'd like**
Ambient light plugin to support Hue like it supports Goovee lights

**Describe alternatives you've considered**
I suppose alternative is just to get Goovee lights instead, but Hue support would be cool if its doable and there is enough people looking for it!

**Comment by SHWotever** [comment]
Hi ! This is _potentially_ on my roadmap ;) however I have a hard time justifying the price of the hue ecosystem, let's take a quick example: a hue play is more than 130€ for 6watts of LEDs (with the bridge), which is a really really high cost per watt. 

I close this as it's already "engaged" in a way, I already bought the test hardware, but I'm still weighing if promoting the most expensive option of all is reasonable. I know that it's already widespread due to some YouTube videos/guides etc... Wait and see ;)
