### ISSUE TITLE
Offset between output frequency and setpoint (custom effect)

### ISSUE THREAD

**Issue by g-prome** [SHWotever/SimHub#1500]
**Describe the bug**
when **custom effect** is used as a **frequency generator** (see screenshot), there is an offset between the desired frequency and the real output frequency

**Simhub version**
9.1.8

**Third party plugins**
None

**To Reproduce**
1. set a custom effect
2. measure the frequency obtained (measurement of sound card signal or bass shaker vibrations)

**Expected behavior**
input= toto => output(Hz) = base effect frequency + (toto/100) x (High effect frequency - base effect frequency)

**Screenshots**
![simhub-hz](https://github.com/SHWotever/SimHub/assets/5487071/916a552c-0fb8-4e05-88e6-efb33e6d8b09)
![output-f-input](https://github.com/SHWotever/SimHub/assets/5487071/3bbb171d-ce22-48dd-bdcd-22509bd8641e)

**Comment by SHWotever** [comment]
Hi ! This is indeed intentional both bounds are slightly offseted to make the settings significant.

For instance if you set a low bound to 40hz it would be associated to a never existing sound (0 gain) 
In the same way the high bound is offseted because a properly tuned effect should not stick to 100% and the higher bound wouldn't be felt neither, making the assigned frequencies completely disconnected to what is happening if they were not slightly offseted. At worse there could be a slight ease in/out to spread those last bits of frequency changed in the extremities.

**Comment by g-prome** [comment]
thank you for this explanation 👍


(for information :
my case is special: I only use custom effects.
I generate dozens of signals based on telemetry, they vary from 0Hz to xxxHz (for example : the many vibrations of the engine, wheels rotation, tyres slip...) so I need fine control 😅

but it's not a problem, I take this phenomenon into account in the ncalc formulas, so that I can generate precise frequencies )


Joyeux Noël ! et bravo pour votre boulot 👏

**Comment by g-prome** [comment]
![image](https://github.com/SHWotever/SimHub/assets/5487071/8b04728d-3cfe-4663-80b3-6c174434c1df)

merci pour la dernière màj !
