### ISSUE TITLE
[Feature request] Button Matrix

### ISSUE THREAD

**Issue by LapoSimoni** [SHWotever/SimHub#1539]
Hi.
I think that it's possible, using diodes like in the attacced file, to simultanesly press buttons.
If yes i suggest to add this info on related wiki page, thank you.

![Screenshot 2024-02-07 171545](https://github.com/SHWotever/SimHub/assets/159291451/05c2f133-43d3-4c3d-9748-6e7978311913)

**Comment by SHWotever** [comment]
Hi ! This pattern allows to indeed to remove the ghosting between rows and columns, but Since simhub is focused on "simple" diy I don't want to support such wiring which involves lot of potential errors (wrong polarity, bad soldering).
Overall since it was out of the scope the code assumes only one "row/column" is active and won't scan for more as indicated in the Read before  : https://github.com/SHWotever/SimHub/wiki/Arduino---Button-matrix#read-before
