### ISSUE TITLE
Opponents object missing car (GT2)

### ISSUE THREAD

**Issue by Butzy79** [SHWotever/SimHub#1544]
In the Opponents object is missing the GT2 Cars in ACC, but not always.
Sometime if you restart the session is ok.
The problem it looks like in broadcasting with the new GT2 Pack

Here you can see from formulas that I expected a different driver in position 18 and it was skipping the real driver in position 18.
Using SDK and accessing broadcasting, car was correctly broadcasted in position 18.
![IMG_8015](https://github.com/SHWotever/SimHub/assets/64496039/ee663d6b-c86b-422b-ac58-f768e22e984c)

**Comment by SHWotever** [comment]
Hi ! 

Would you have a simhub replay when this happens ?
Overall simhub reorders the lines to have real time position (the broadcast api is reordering positions really deferred so the realtime position and the leaderboard position might not be the exactly the same and it's important to see the whole data set.

Additionnaly you can see the whole dataset of data using this page: http://127.0.0.1:8888/diaglb.html having a good overview allows to better understand what is going

**Comment by Butzy79** [comment]
Hi My friend,
I still have open ACC with this error.

I can register one and send it here?

Ricky Scotti
Handy +41.79.8130637

**Comment by SHWotever** [comment]
Yes for sure ;)

**Comment by Butzy79** [comment]
Here there wetransfer of the replay:
https://we.tl/t-1hrlI5PBxr

And here the picture of the localhost at port 8888

￼

As you can see it is missing the position 19 now.


Ricky Scotti
Handy +41.79.8130637

**Comment by Butzy79** [comment]
![IMG_8016](https://github.com/SHWotever/SimHub/assets/64496039/306ae0db-b1e3-4711-99c9-2e80128bfd1e)

**Comment by SHWotever** [comment]
Thnaks ! I checked the replay and there reason is  because the player data are invalid, it does not have any position on track :
![image](https://github.com/SHWotever/SimHub/assets/2207331/91cc56ef-b6ff-49d3-a360-199e6724b4dd)

The data is indeed here, but since it's invalid it's rejected. Only cars with complete data are being processes (filters which is not applied by the broadcast api demo)

**Comment by Butzy79** [comment]
Ok, but is a new session, not even started, only entered.
What can I do for fix it?
:)

**Comment by SHWotever** [comment]
I will see if I remove this filter if I get correct data, since the broadcast api is a little messy I originally added this filter to ensure the true data were received to avoid data corruptions with initialized values. But due to more issues with grid being "delivered" one player at once by the api I'm now waiting one full second before adding it, so it should be enough to workaround the original issue and remove this "0" splineposition filter. Seeing the order I guess it's truly at 0 (which is statistically a very low probability, but who knows ? :D)

**Comment by SHWotever** [comment]
Hi ! The change has been released !

**Comment by Butzy79** [comment]
I love u bud!

**Comment by Butzy79** [comment]
Hi,
I think this fix caused another bug.
Now, with Version 9.1.30 ONLY in ACC, if I do a single race, all the car has position 0, but with other sims like ac, ams2, iracing not, it works smoothly.
If I install 9.1.29 everything is fine, expect this issue with Gt2 cars.
here a screenshot with 9.1.30
Shall I open another bug report?
![IMG_8033](https://github.com/SHWotever/SimHub/assets/64496039/982ebb38-4340-4d7c-8a7f-6d534c61f4fc)

**Comment by SHWotever** [comment]
Hi ! I will take a look!

**Comment by Butzy79** [comment]
Bud I saw your fixes.. I love you !
