### ISSUE TITLE
Force Enable Dark Mode

### ISSUE THREAD

**Issue by josap97** [SHWotever/SimHub#1551]
**Describe the bug**
A recent SimHUB update seems to have force enabled a dark mode and there does not seem to be an option to use a normal, readable, useable mode. Will not be able to use SimHUB until any such problem has been resolved.

**Simhub version**
V9.2.2

**To Reproduce**
Seems to happen after recent SimHUB update.

**Expected behavior**
Expect not to be force to use a dark mode to burn weird patterns into your eyes.

**Screenshots**
![image](https://github.com/SHWotever/SimHub/assets/13086059/4c51b4f0-5366-4c28-b989-06e47cbbef49)

**Comment by SHWotever** [comment]
Hi !

For more consistency and easier maintenance the "white theme" has not been ported on this new UI. Unfortunately maintaining both light and dark mode was really an extremely hard task due to the high number of customized components. And the "quirks" in the white theme we're multiplying. So this new UI now focuses on single scheme with a better consistency instead of having two not correctly handled.

**Comment by josap97** [comment]
That is incredibly disappointing to hear and will mean that I will not use SimHUB anymore until such time as this decision is reversed as having to read bright text on a dark background is very uncomfortable bordering on painful.

**Comment by SHWotever** [comment]
Unfortunately decision had to be made. Simhub is relying on a single developer (me) and the perimeter is extremely wide. I can understand dark color scheme is not your preference. But maintaining two color scheme was slowing down improving SimHub and preventing keeping a consistent UI. I wish I could maintain both, I have a really strong culture of "if it exists don't remove it", but It was not possible anymore and this strong decision had to be taken.
