### ISSUE TITLE
on Xbox Series FH5 works but not FH4. Don't receive data

### ISSUE THREAD

**Issue by JMA3146** [SHWotever/SimHub#1572]
**Describe the bug**
on Xbox Series FH5 works but not FH4. Don't receive data

**Simhub version**
9.2.4

**Third party plugins**
xbox series

**To Reproduce**
try to connect FH4 on xbox series > Simhub 

**Expected behavior**
receiving data

**Comment by SHWotever** [comment]
Hi !

Unfortunately FH4 telemetry is known to be broken on XBox S/X  : https://support.forzamotorsport.net/hc/en-us/articles/360001991068-FH4-Known-Issues

Unfortunately they classified it in "won't fix" category, so there is no hope of an improvement later : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/843c1ada-1e4b-4b50-bfad-d6ccc06dd34c)

That's why it's not listed in the "known to be working" games here : 
https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting#about-consoles-configuration

Nicolas
