### ISSUE TITLE
SimHub Freezing when selecting any of the F1 XX games.

### ISSUE THREAD

**Issue by lewisdevelop** [SHWotever/SimHub#1579]
**Describe the bug**

On running simhub with F1 23 or 22 selected, simhub will have random freezes followed by regular speed and freezing again.

**Simhub version**
Make sure to run the latest version
9.2.7

**Third party plugins**
Make sure to disable first any third party plugins (It's a critical step before reporting any freeze/performance/crash issues)
New Install of SimHub (tried hard-reinstalling without backing up)

**To Reproduce**
1. Open SimHub with F1 23/22 selected
2. Thats all you need to do.

**Expected behavior**
For it to run at regular speed at all times

**Screenshots**
Video: https://www.youtube.com/watch?v=wrtEuSG97D0

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).
Logs Folder: https://drive.google.com/drive/folders/1TSrEZ6tA9VacA3S9QnJAvozTpmY__4Y_?usp=sharing

**Comment by SHWotever** [comment]
Hi !

Since it's only occurring when choosing a codemasters game, I would think it's bound to network.

Do you have any other applications around which may send data or forward data to 27777 ? 

Can you try to change the used UDP port to something else like 28888 ? If somehow you can't change it due to the freeze, 
you can edit `C:\Program Files (x86)\SimHub\PluginsData\GameSettings.json` locate `F12022` or `F12023`and set the udp port here (While simhub is closed) : 
![image](https://github.com/SHWotever/SimHub/assets/2207331/2bc9f6d8-0da8-467c-b49d-053a3a8d77e4)

Do you use any specific firewalls/antivirus/vpns which could interfere with network ? (Windows Defender should be fine on this )

**Comment by lewisdevelop** [comment]
No VPN or Windows Defender.
Changed port, still getting lag

**Comment by SHWotever** [comment]
Hi ! Thnaks for your feedback,

Does it happens on some other UDP games like dirt rally 2 ?

Could you try to disable all the plugins in settings to see if it helps ? That's not ideal but it will allow to target either it's bound specifically to the game or to one or more major simhub features.
If the issue stops  could you try to enable them again one by one ?

**Comment by SHWotever** [comment]
That could be some UI lag are you using Freesync or Gsync over "windowed" applications (this is a setting graphics card ? This often hits hardly WPF apps UI up to a freeze.

**Comment by lewisdevelop** [comment]
I already tried turning off Gsync and I don't have Freesync

**Comment by lewisdevelop** [comment]
I forgot to do what you mentioned in your first reply but that has worsened the issue. SimHub is now unresponsive for longer.

**Comment by lewisdevelop** [comment]
I ended up restarting my PC via the PSU and simhub suddenly started working.
