### ISSUE TITLE
Fanalab crashing after time when Simhub is running (ACC)

### ISSUE THREAD

**Issue by betaeffect** [SHWotever/SimHub#1600]
**Describe the bug**
I'm running some programms which are using the telemetry data from ACC and didnt have any problems with them so far.
Now I need to use Simhub to send telemetry data via UART to a microcontroller.
My problem is that it's working at start but after some time Fanalab is crashing and my wheel stopps working.
If I dont run Simhub the issue does not appear.
My guess is that it does have something to do with the UDP protocol but cant find any information on that.

**Simhub version**
9.2.12

**To Reproduce**
1. Start Fanalab and Simhub
2. Start ACC
3. Drive a race and after some time fanalab crashes

**Comment by SHWotever** [comment]
Hi ! There shouldn't be any direct interferences between fanalab and simhub at least nothing I can see directly. 

Can you contact fanalab to know the cause ? Unfortunately without a clue about what could be conflicting in your case I can hardly give insights about how to solve your issue. 

Maybe if you have log files from fanalab showing the crash so I could deduce the root cause ?
