### ISSUE TITLE
Control Mapper Stream Deck

### ISSUE THREAD

**Issue by Pringels1977** [SHWotever/SimHub#1606]
Hello, I'm having an issue with the SimHub Control Mapper for Stream Deck. It used to work perfectly fine, but now I'm getting a message saying it has no connection. I've tried reinstalling SimHub, allowing it through the firewall, and running it as an administrator, but I'm still stuck. "Whether it's the original plugin or the one by Martin, the role is empty."

> 
![Screenshot_2024-05-03_140130](https://github.com/SHWotever/SimHub/assets/99821323/e7a99e20-998b-4076-8ad7-624cecf50588)
![Screenshot_2024-05-03_140310](https://github.com/SHWotever/SimHub/assets/99821323/527a95f5-80e8-40e6-bc2e-72860a11af7f)

**Comment by SHWotever** [comment]
Hi ! Could you join the simhub log files ? https://github.com/SHWotever/SimHub/issues/new?assignees=&labels=triage&projects=&template=bug_report.md&title=

Overall I would think simhub is not running with the default 8888 port in the global settings. This can be because you changed it manually, or eventually due to another application already using it.

**Comment by Pringels1977** [comment]
Solution The port 8888 was being used by another program from Intel 
Thanks
