### ISSUE TITLE
[Question] Is there a specific reason why to not support leds like SK6812/b?

### ISSUE THREAD

**Issue by mathias21** [SHWotever/SimHub#1643]
There are amazing SK6812 led formats that I would love to use in my custom wheel. Arduino supports them easily, even just by making use of the same neopixel library that Simhub generated arduino file already contains. I've been trying to setup several of them but none were working with Simhub.

Is there any specific reason why this is not supported? Is there any specific way I can help making this possible? I would love to have a collaboration space where we could help developing this amazing piece of software with some Pull requests.

**Comment by mathias21** [comment]
It seems that reinstalling Simhub downgrading to 9.1.12 (I think that was the version) made this work. Unsure if any custom arduino code was left behind. I can blame that for now and will retest against latest version as soon as I get some spare time.

**Comment by SHWotever** [comment]
Hi ! In theory the LEDs code has not been changed for a very long time. Probably the last time around 3 or 4 years ago (6.x simhub versions probably) 

The SK6812 if I'm not wrong are rgbw. All effects in simhub are RGB. Rgbw finds applications in ambiant lightings but I see no real possibility to include a white component in all whole effects chain without introducing excessive complexity, that's why adding support for such LEDs would be misleading (with no white channel control, it would not be really used) so I prefer not to add it and stay on well known RGB ws2812 RGB LEDs.

**Comment by mathias21** [comment]
Sure, no problem with excluding white component at all. I had tested cable, pro micro board, solder joints, etc, but the problem seemed to be Simhub instance, which may have some custom arduino code I've did time ago that could be impacting led config. 
In any case, thanks for answering and keep up with the amazing work you do here!
