### ISSUE TITLE
Stuck on "Searching for game readers..."

### ISSUE THREAD

**Issue by Rewbin101** [SHWotever/SimHub#1671]
**Describe the bug**
This is my first time installing simhub and when launching the app after installing the loader gets stuck on Searching for game readers

**Simhub version**
9.4.4

**Third party plugins**
First time was an install as normal with other apps open, second (fresh) install all other apps were closed.

**To Reproduce**
Just downloading and running the app, can't get any further.

**Log files**
[SimHub.txt](https://github.com/user-attachments/files/16694308/SimHub.txt)

**Comment by Rewbin101** [comment]
This error code found in the logs also affects my Asseto corsa with the same error code.
( i have never received this code until installing Simhub dashboard)
So this is either a simhub caused issue or a windows issue that just happened today and is ruining my day

**Comment by SHWotever** [comment]
Hi ! Seeing the error and the fact as another application has the same issue it appears to be some kind of .net framework (a windows component) corruption. I would try to check for recovery point in case this has been caused by some installation. Microsoft has a repair tool, I never tested it myself but it could help : https://support.microsoft.com/en-us/topic/microsoft-net-framework-repair-tool-is-available-942a01e3-5b8b-7abb-c166-c34a2f4b612a
