### ISSUE TITLE
Vocore screen undetectable by SimHub

### ISSUE THREAD

**Issue by nguyennguyen4** [SHWotever/SimHub#1672]
**Describe the bug**
The "Generic Vocore screen" device suddenly stopped detecting my Vocore screen.

**Simhub version**
9.4.4

**Third party plugins**
None

**To Reproduce**
Unknown how

**Expected behavior**
Vocore screen to be detected

**Screenshots**
@![Screenshot 2024-08-22 195323](https://github.com/user-attachments/assets/f3d8aa75-5d45-442b-ac47-fdeec9c648cb)

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
[SimHub.txt](https://github.com/user-attachments/files/16715712/SimHub.txt)

**Additional context**
Problem occured after BIOS update

**Comment by SHWotever** [comment]
Hi ! I see from the logs that the usb communication dll can't be loaded could you check that it's still in simhub install directory? libusb-1.0.dll, if it's not here please make sure your antivirus is not simply deleting it.

If it's still here it's likely to be VC+ corruption. Then trying to repair VC++ using the installer could help : https://aka.ms/vs/17/release/vc_redist.x86.exe

Let me know if it helped,

**Comment by nguyennguyen4** [comment]
It did! Mega thanks a lot!
Just for informative purposes though, any idea why this suddenly happened (considering the additional context given)?

**Comment by SHWotever** [comment]
That's the microsoft mysteries impacting all the applications ;) Unfortunately it's hard to tell, it could be an installer "crushing" the good dlls, it could also be an update which did not went correctly, just unistalling vc++ during a computer cleanup (like picking anything you don't know in add or remove apps), or just a corrupted file. 
I can't see how bios update could break vc++, usually it's more sneaky like usb instabilities, BSOD etc ... if the new bios has issues. I think that the bios update and the issue matching in time is just a fortuity, that's why I did not focused on this in my previous reply. In all cases this saved you lot of future struggle ;) VC++ broken means that you would have lot of applications and games crashes. 

Happy to hear it was nothing more sneaky than my original thought ;)

Nicolas
