### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Carlos-57** [SHWotever/SimHub#1693]
SinHub has not been reporting any new updates for a while now. I have the update on startup enabled and it doesn't do it. Right now I have a version older than the latest one so you can see there is no new version message.
Thanks.
![Captura de pantalla (12)](https://github.com/user-attachments/assets/00b3f473-07e4-48e6-9295-634de785902e)

**Comment by SHWotever** [comment]
Hi ! This was due to antivirus wrongly hitting new versions when a spike of users switching to the new version was triggered by the new version notification. Due to that I had to suspend any new versions notifications. 

In the latest version I've included a smarter check based on release dates allowing to properly defer the notification and hopefully avoid this issue. If unfortunately the antivirus still do false claims, I fear I will be forced to keep new version notifications disabled.

You can read the whole explanation about antivirus false positives here https://github.com/SHWotever/SimHub/wiki/Antivirus-false-positives

**Comment by Carlos-57** [comment]
OK thanks
