### ISSUE TITLE
New problems with Govee lights

### ISSUE THREAD

**Issue by HoonyTunes** [SHWotever/SimHub#1719]
**Describe the bug**
Hi there, you helped me with my Govee light problem a couple of weeks ago and we (you) fixed it by identifying some Govee lights were sending longer messages than allowed by SimHub (something like that). Anyway, I've added two more Govee light strips to my setup and now new problems are emerging. Lights keep disconnecting and switching to their default colour during gameplay, or freezing having captured a particular screen state. What's more, when I shut down my rig, previously all my lights would revert to their default, which was great because the room would light up and make it easier to exit the rig or the room – now, though, after adding the two extra lights, it takes several minutes sometimes to resume their default state (not a screen cap).

It's particularly odd because some lights keep working as expected at any given time, with one or two bugging out, then they'll bug back in and start working again, only for a different light or lights to take on the same problem.

**Simhub version**
9.4.9 (latest)

**Third party plugins**
Done

**To Reproduce**
All in the explanation above

**Expected behavior**
As before, lights changing according to screen capture areas as they were before.

**Screenshots**

**Log files**
[SimHub.6.txt](https://github.com/user-attachments/files/17308603/SimHub.6.txt)
[SimHub.3.txt](https://github.com/user-attachments/files/17308604/SimHub.3.txt)
[SimHub.2.txt](https://github.com/user-attachments/files/17308605/SimHub.2.txt)
[SimHub.1.txt](https://github.com/user-attachments/files/17308606/SimHub.1.txt)
[SimHub.4.txt](https://github.com/user-attachments/files/17308607/SimHub.4.txt)
[SimHub.5.txt](https://github.com/user-attachments/files/17308608/SimHub.5.txt)

How to attach files : https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Based on the symptoms and the logs it looks like the lights does not reply and gets disconnected. 
Is there any weaknesses on the wifi side ? Does it still happens when you power off for instance half of them ?

About the exit status it's now set explicitly per light instead of trying to keep the last status which was unreliable when quickly switching them on/off in simhub.
![image](https://github.com/user-attachments/assets/e6b1ae36-6cc5-4767-8809-61536b85c1d1)

**Comment by HoonyTunes** [comment]
I hadn't thought of that. Let me do some experiments with router positioning and I'll get back to you. Thank you.

**Comment by SHWotever** [comment]
By default it's checked and set them off at disconnect,  otherwise it will just let them go back to their previous "not dreamview" state. 

But that only works when the connection is steady, if it's already disconnected due to the instabilities you are having it won't  be able either to disable the "dreamview" state (and go back to the colors) or shut it off no matter the option

**Comment by HoonyTunes** [comment]
Okay, well, this is embarrassing – it turns out that moving my router has massively improved the Wi-Fi reception of the lights and seems to have fixed the issue. Thanks for helping me find the problem, regardless. It's very much appreciated.

**Comment by SHWotever** [comment]
Ha ha no worries :)

Don't laugh, as usual when a bug is reported I start rushing on testing, and the network cable to my wifi access was loose, making random disconnects too. It was not about wifi reception but the same symptoms.
