### ISSUE TITLE
Iracing Beta UI - Game active

### ISSUE THREAD

**Issue by lamaug** [SHWotever/SimHub#1721]
**Describe the bug**
When Iracing Beta UI is opened, Simhub defines Iracing as the Active Game. So to utilize Simbhub with any other game, the Beta UI should be closed .
Normal behavior would be to define Iracing as the active game only when iRacingSim64DX11.exe is started. So we keep the Beta UI in the background as we do with Steam, Xbox app etc..

**Simhub version**
9.4.11

**Comment by SHWotever** [comment]
Hi !

This is by design, just like any other games is detected when it get's started, IRacing is getting "started" when the UI is launched,

You can remove the UI process detection by modifying C:\Program Files (x86)\SimHub\SimHubWPF.exe.config and remove iracingui from it.
![image](https://github.com/user-attachments/assets/af1a1505-d416-4d28-b3ad-58dc5336c947)
