### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by LoermansA** [SHWotever/SimHub#1742]
**Is your feature request related to a problem? Please describe.**
The Simhub installer is not signed and Windows nags about this every time I run an update. Not a major problem because I can install it anyway but having the installer officially signed gives a little peace of mind when it comes to all the malware floating around.

**Describe the solution you'd like**
I would like the installer to be signed and trusted by Windows.

**Describe alternatives you've considered**
Alternative is to accept the risk of using a non signed executable.

**Additional context**
N.a.

**Comment by SHWotever** [comment]
Hi ! Actually the next version will be signed, Antivirus harassing made me pay the "tax" :D. But it won't remove the defender nag completely, at least at first, time to build some reputations over the certificate.  EV certificate are only accessible to named companies, not independent individual professionals.

![image](https://github.com/user-attachments/assets/70e28335-0d97-4662-aed6-85a883e7292a)

**Comment by LoermansA** [comment]
Amazing, thanks for the incredibly quick response! And I understand that there is a cost involved and I would totally understand a little price increase for getting the installers signed. Let me know if I can help in any way because I love your product!

**Comment by SHWotever** [comment]
Thanks for your feedback ! 

Price was a factor, but not only, on the principle I'm totally against the concept of marking exe/installers as malware "for a short time" just because they are not signed (signature does not change any of the content, the behaviour or anything else). 

I've been battling for many years with so many submissions to Windows Defender false positives website. I finally gave up as the fear of false positives after every new releases was now overwhelming :D

**Comment by LoermansA** [comment]
I understand. Is releasing through Steam an option then?
