### ISSUE TITLE
Compatibilidad volante akira F1 simulaje

### ISSUE THREAD

**Issue by giancarlocastle** [SHWotever/SimHub#1748]
Muy buenas , estoy con un volante akira wheel de Simulaje, y queria comentarte de si hay posibilidad de que exitiera compatibilidad con este volante. Ya que usa software propio pero ya creo que no tiene soporte. 
Solo sé que el volante no utiliza arduino, pero he pensado si hay posibilidad hacerlo funcionar mediante algun plugin o algo parecido.

**Comment by SHWotever** [comment]
Hi ! This wheel uses a proprietary screen not capable of receiving prerendered bitmaps (required for dash studio support)

This looks closer to the nextion which got deprecated a few years ago in Simhub (due to it being too limited as well as the manufacturer blocking advanced usages such as SimHub).

For that reason I can't support such screen, If the wheel gets updated in the future with a more powerful screen capable of full bitmaps rendering I will be able to support it (with the help of the manufacturer if they allow/want simhub compatibility).
