### ISSUE TITLE
"Use game specific setting" in Bass Shaker module defaults to none

### ISSUE THREAD

**Issue by o2dazone** [SHWotever/SimHub#276]
Maybe it's a usability issue, but it's a little unclear what's supposed to happen when clicking "Use game specific settings" in the Bass Shaker module. Everything gets zero'd out. I feel like there should be some way to set a 'default' profile, so all non game-specific settings can inherit from.

**Comment by zegreatclan** [comment]
Actually when you uncheck game specific you fall into a default profile, since I've made a default profile for all the major games I've retested this default profile since a few releases and  it makes less sense to keep that option. 

Concerning per effect inheritance to a default profile, that would be interesting, and I tatally aggre  on the idea itself ;) however it would add a little too much complexity to the user experience, time has learned me that I have to keep things simple (I've not yet achieved to fix all the past in Simhub :D) and sometimes I must retain myself to add some usability things  to avoid confusion. 

I also want to keep a profile as a single "unit" which can be exported and imported at will and this would not match any kind of "global profile inheritance".

**Comment by o2dazone** [comment]
I never considered cluttering up the UX to be a factor, I agree it would be confusing knowing whether or not it's using a custom profile or a global one. Your "Sync settings" dropdown for individual effects makes a lot of sense to me. I mocked out swapping the 'Use game specific settings' checkbox with a dropdown similar to your 'sync' for effects

![aa](https://user-images.githubusercontent.com/1907517/45932257-8248a580-bf2e-11e8-8e8d-8fe7cb79fb16.png)

I might be the odd man on this, and everyone else likes to custom-tweak their per-game settings, but I don't change my settings too much, so it's not a lot of hassle to export/import it when i make changes (I only play two racing games, I could see this being a pain for someone who plays more)

**Comment by zegreatclan** [comment]
No worries, if the pile is big it means there is still lot of potential and fun work coming :D
Concerning the inheritance, the "sync from" is actually one of the examples of what lot of peoples don't understand, even if you and me understands it and it's purpose.

I think a nice compromise could be to simply allow a "copy from" where you could pick the game and get back it's settings.
