### ISSUE TITLE
Push Button LED Support

### ISSUE THREAD

**Issue by MIkes285** [SHWotever/SimHub#409]
Hi, 
 I have sourced some momentary push buttons that have 3v LED in them.
would it be possible to implement normal -+ leds to light up or flash, 
for example, red LED button is presses for pit limit, the led will flash when pit limit data is on?

Regards
Mike

**Comment by SHWotever** [comment]
Hi! I'm afraid simple LEDs are not supported, basically, in case of abuse, it would burn the Arduino. 
You can read this excellent article about it (Chapter 10)  : https://www.rugged-circuits.com/10-ways-to-destroy-an-arduino. Since I want to avoid any risks for people I really can't add this feature I'm sorry.

As a workaround you can use the following entry point to drive unsupported hardware : https://github.com/SHWotever/SimHub/wiki/Custom-Arduino-hardware-support
