### ISSUE TITLE
Font on android doesn't match the font on PC

### ISSUE THREAD

**Issue by Kesh2430** [SHWotever/SimHub#418]
This issue occurred after I had to reset/reinstall Windows 10 and therefore had to reinstall Simhub. I've downloaded my dash and imported it into Simhub just fine and also the .ttf files to go with it. After changing the font in Simhub, the font on my android phone no longer matches the font shown on Simhub. Why is this? 

Correct Font
![Correct Font](https://user-images.githubusercontent.com/55858688/65728822-15716980-e0b4-11e9-9fa5-248192860550.png)

Incorrect Font
![Incorrect Font](https://user-images.githubusercontent.com/55858688/65728862-2fab4780-e0b4-11e9-826b-f6c620430398.png)

**Comment by SHWotever** [comment]
Hi! 

Could you try to clear the browser file cache to make sure that the browser receives the latest font definition from your computer ? 
https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DAndroid&hl=en

If it's not enough could you send me the dash so I can inspect it ?

Nicolas

**Comment by Kesh2430** [comment]
[Scania Dash 2.1.zip](https://github.com/SHWotever/SimHub/files/3664405/Scania.Dash.2.1.zip)

It still hasn't worked. I've uploaded the dash. The font I've used for the speed and time was downloaded from https://www.dafont.com/ww-digital.font?fpp=100&text=1234567890

**Comment by SHWotever** [comment]
Hi! After some research it looks like the latest windows 10 major version now uses two folders for fonts instead of the "good old" "c:\windows\fonts", to workaround that make sure to install in the classic folder you need to right click on the fond and select "install for all users"(sorry for my frenchy screenshot :D),
![image](https://user-images.githubusercontent.com/2207331/65803665-8cbfff80-e17f-11e9-9b46-8279bf24175d.png)

 then restart simhub and reload the mobile dash, the font should be taken into account.

I've added a fix for the next simhub version so this new font folder will be taken into account.

**Comment by Kesh2430** [comment]
You're an absolute legend! Thank you for your help, really do appreciate it! :)
