### ISSUE TITLE
Shakeit taking over volume control

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#421]
Hi!
Since I also use my shakers for music or non telemetry based/non racing game, I'd like to be able to keep manual control over the volume (talking about the Windows settings) of each of my sound outputs.
Could the ShakeIt overall gain be dissociated from the enabled sound outputs volume please?
Or may be ShakeIt controlling the output volume could be an option (in general or even per output)?
Thanks for considering the idea.

**Comment by SHWotever** [comment]
Hi ! Controlling sound card volume was a deliberate choice to avoid issues with volume or muted outputs, since secondary sound cards are hard to control, I choose to force volume to make sure there would not be any issues on this particular point.
I could add that option but in this case Simhub would not control anymore the sound card volume, in this case the global gain setting would not have any effect anymore, not sure if it's a good deal.

**Comment by SHWotever** [comment]
Actually I've ended with the choice over "sound card volume" or "generated sound volume"
![image](https://user-images.githubusercontent.com/2207331/65818465-deb16580-e211-11e9-9259-b590f8da29da.png)
In case you choose "generated sound volume", Simhub will make the sound volume vary instead of controlling the sound card volume.

**Comment by Romainrob** [comment]
Nice! This looks like the perfect solution.
Thank you very much for that! :)

**Comment by SHWotever** [comment]
Released with 6.7.8, thanks again for the feedback !
