### ISSUE TITLE
Support for Adafruit Alphanumeric backpacks

### ISSUE THREAD

**Issue by johnnyverhoeff** [SHWotever/SimHub#423]
https://www.adafruit.com/product/1911

They use the same chip as the HT16k33 7 segements module
for which there is already support
Adafruit has a lib also for it its in the Adafruit_LEDBackpack.h and Adafruit_GFX.h
object is called: Adafruit_AlphaNum4
Many thanks

**Comment by SHWotever** [comment]
Hi! Is there any good source for such hardware? Adafruit price tag is obscene (kind of :D) with a 25$ bill (with shipping) for one. That's really above the maximum price tag I try to respect for Arduino parts.

**Comment by johnnyverhoeff** [comment]
I bought 4 of these on Mouser, but they're the same price as from adafruit, 10 dollars.
I did a quick search on the interwebs but couldn't find anything similar and cheaper.

But since you already support the same Chip in SimHub, i figured it would relatively easily to support.

But I understand if you don't want to put the time/effort in it.

**Comment by SHWotever** [comment]
Actually since it's a full alphanumeric display it would be worth redoing all the fonts to match it (Simhub only uses 7 segments displays for now), which is really huge and boring work :D moreover if the price tag restrains the potential users. 
But I found some clones on banggood at a fair price ;) https://www.banggood.com/fr/5pcs-4-bit-Pozidriv-0_54-Inch-14-segment-LED-Digital-Tube-Module-Red-I2C-Control-2-line-Control-LED-Display-Screen-Module-p-1565759.html?utm_design=41&utm_source=emarsys&utm_medium=Neworder171109&utm_campaign=trigger-emarsys&utm_content=winna&sc_src=email_2675773&sc_eh=d40481a8f7f3067f1&sc_llid=16212763&sc_lid=105229698&sc_uid=RQopwvyaTO
I ordered a pack, wait and see ;)

**Comment by johnnyverhoeff** [comment]
I 'hacked' the LCD driver in Simhub and also tried custom protocol in SimHub to get these to work (sort of) and you can just send normal chars to the display, so relatively easy, no fonts needed I think, depending on your SimHub implementation of course.

Thank you for your support, I will donate some bucks your way (i already have a license) to show my appreciation.

**Comment by jeangagnier** [comment]
> 
> 
> I 'hacked' the LCD driver in Simhub and also tried custom protocol in SimHub to get these to work (sort of) and you can just send normal chars to the display, so relatively easy, no fonts needed I think, depending on your SimHub implementation of course.
> 
> Thank you for your support, I will donate some bucks your way (i already have a license) to show my appreciation.

I'm necroing this thread, I was wondering how you managed to get around it.

They're very cheap from Chinese providers these days (like, 2-3 dollars/euros per unit), and it would be nice to know that it works before I order a dozen :D.

**Comment by SHWotever** [comment]
Hi ! I clase this, with the spreading  of full lcds text components are getting less and less used. Current supported devices is wide enough compared to the use.
