### ISSUE TITLE
ShakeIt for bass slip effect low sensitivity

### ISSUE THREAD

**Issue by maikol000** [SHWotever/SimHub#430]
I recently updated Simhub v6.8.6 to Simhub v6.8.8 and with Assetto Corsa the wheel slip effect sensitivity for ShakeIt for bass shakers is now too low. With 6.8.6 I could configure wheel slip to get feedback from front tyres beeing on the edge of slipping. With 6.8.8 the front wheels only slip when the tyres are beyond recovery or locked. I wen't back to 6.8.6 and it works fine.

**Comment by SHWotever** [comment]
hi!

Actually I had many opposite reproachs about wheel slip that's why I made it more contrasted by default (reaching slower the max effect), but you can compensate easily this new "pre-calibration" by raising the gain here : 
![image](https://user-images.githubusercontent.com/2207331/66938353-53bdd100-f041-11e9-9da2-82e90c1cfad9.png)

Also if you focus on braking do not hesitate to use the wheel lock effect, it will allow you to catch precisely wheel locking or locking start. I've added a new algorythm based on wheel speed data giving back precisely what is happening to wheels .

Let me know if it helped,
Best regards,

Nicolas

**Comment by maikol000** [comment]
Hello,

and thanks for the quick response. I already tried the input gain increase but for some reason it just didn't behave as I hoped. The early slip is just not showing as it does with 6.8.6 even if I go to some 300 gain. I can hear the tires squeal and see the traction loss but is see no response in the live effects. I may be doing something wrong as I only played with 6.8.8 for a little while. With 6.8.6 I get also tire lock ok with the wheel slip function so I'm fine with 6.8.6 for now.

Btw. is there some file tweak etc. I could use to have 6.8.6 wheel slip with 6.8.8 and later?

Br,

 Mika

________________________________
Lähettäjä: Wotever <notifications@github.com>
Lähetetty: keskiviikko 16. lokakuuta 2019 19.20
Vastaanottaja: SHWotever/SimHub <SimHub@noreply.github.com>
Kopio: maikol000 <maikol000@hotmail.com>; Author <author@noreply.github.com>
Aihe: Re: [SHWotever/SimHub] ShakeIt for bass slip effect low sensitivity (#430)


hi!

Actually I had many opposite reproachs about wheel slip that's why I made it more contrasted by default (reaching slower the max effect), but you can compensate easily this new "pre-calibration" by raising the gain here :
[image]<https://user-images.githubusercontent.com/2207331/66938353-53bdd100-f041-11e9-9da2-82e90c1cfad9.png>

Also if you focus on braking do not hesitate to use the wheel lock effect, it will allow you to catch precisely wheel locking or locking start. I've added a new algorythm based on wheel speed data giving back precisely what is happening to wheels .

Let me know if it helped,
Best regards,

Nicolas
