### ISSUE TITLE
Fault Message Box - I don't know what to do...

### ISSUE THREAD

**Issue by hobili** [SHWotever/SimHub#435]
Hello,

when starting SimHub I get a message box, but the program is running fine when I click "ok". 

unfortunatly I can't attach a screenshot..

The Message reads:

An error occured while loading plugin SimHub.Plugins.Web-WebPlugin: System.Net.Sockets.SocketExeption(0x80004005): 

and so on...

What can I do? I uninstalled and reinstalled the program inclusive deleting the Folder of the program. 

br
Holger

![image](https://user-images.githubusercontent.com/56883534/67636669-41f6ec00-f8d3-11e9-8d2f-457cd73b9135.png)

**Comment by hobili** [comment]
Oh, the screenshot worked ;-)

**Comment by SHWotever** [comment]
Hi ! It means the another software is using the same port as simhub for web acccess (8888 or 8889)
If you can't locate the other app you can change the simhub ports it in settings here (you can try 9998 for instance instead of 8888), then restart Simhub:
![image](https://user-images.githubusercontent.com/2207331/67636730-cfd2d700-f8d3-11e9-871c-683016db7bbf.png)

It could be also your firewall blocking access, you can try to disable it temporary to see if it helps, if it helps make sure to add the appropriate exceptions.

In this situation, most of the features will still work but anything requiring this component will fail (inside help, remote dash, mobile access ....)

Let me know,
Best regards

**Comment by hobili** [comment]
Thank you very much - I don't really know which program this could be - I didn't installed anything. But anyhow - I changed the port and the message box is gone! ;-)

**Comment by SHWotever** [comment]
Perfect ! Have fun !
