### ISSUE TITLE
iRacing Blue Flags, start of race

### ISSUE THREAD

**Issue by Meekstaaa** [SHWotever/SimHub#436]
Hey,

I've put this up before but the blue flag at the start is still happening. But with RomainRob's iRacing flag dll the blue flag issue isn't present.

**Comment by SHWotever** [comment]
hi ! I've checked I've seen that the RomainRob's plugin (not the dash) would behave the same, but I think I've finally found the trick , the green flag has higher priority (I've took a look in iflag app and its the case too), so I've disabled blue flag as long as green is active that should be enough hopefully :D

**Comment by Romainrob** [comment]
Hi! J'ai les oreilles qui sifflent :)
The blue flag is triggered at the race start because, before the line, your current lap is 1 for some reason. When crossing the line it goes up to 2 for a few seconds then back to 1. As the same thing happens for the car behind you, it's as if it was a lap ahead for a moment.
I used the same trick on my dash, disabling the blue if the green is out, but only if the current lap <=2. As the green last for a long while, and you may still want the blue flag to work just after a race restart.

**Comment by SHWotever** [comment]
Fix published with the final release ! Have fun !
