### ISSUE TITLE
Connecting to horizon 4

### ISSUE THREAD

**Issue by WillCooney** [SHWotever/SimHub#442]
Sorry if this seems like a stupid question but I'm new to simhub and can't figure it out. With other apps it gives the UDP port address and the IP that needs to be entered into horizon but with simhub it gives me the port but not the IP. I've spent ages trying to troubleshoot so would very much appreciate a response.

**Comment by SHWotever** [comment]
Hi ! You simply need to configure the game to send on 127.0.0.1 /8000 as shown on the instructions :
![image](https://user-images.githubusercontent.com/2207331/69478733-14c82b80-0df6-11ea-9de3-78ddaa8de030.png)

Instructions can be opened here : 
![image](https://user-images.githubusercontent.com/2207331/69478739-2c9faf80-0df6-11ea-94d2-2271530655c8.png)

If you are running from a console, you need to enter your computer ip instead of 127.0.0.1

If you have issues you can read the full game configuration and troubleshooting guide here : https://github.com/SHWotever/SimHub/wiki/SimHub-Basics----Games-config-and-troubleshooting
