### ISSUE TITLE
Richard Burns Rally

### ISSUE THREAD

**Issue by OneDadz** [SHWotever/SimHub#447]
Bonjour,

Hello,

Games: Richard Burns rally

Not Arduino

Equipment:
Fanatec csl v2.5
V3 crankset
Subpac 2

[SimHub.log](https://github.com/SHWotever/SimHub/files/3886172/SimHub.log)

New installation of windows 10, RBR install, works, as soon as,
 i install Simhub RBR lag sound and image.

when I uninstall Simhub, RBR lag always.

Cordialy,

David

**Comment by SHWotever** [comment]
Hi ! 
Thnaks for the feedback !

I guess something else is causing the lags, Simhub does not modify the game files in any ways. Which means that the game should get back to its normal behavior when uninstalling if it was caused by SimHub. Have you checked any other potential "interfering" softwares (antiviruses ....) which could have changed at the same time ?

PS : The log you sent is related to IRacing, do you have a log after trying RBR ?

**Comment by OneDadz** [comment]
[SimHub.log](https://github.com/SHWotever/SimHub/files/3886774/SimHub.log)


that's exactly the logic I have. I went through the factors that could cause problems.

and after installing windows, configure all my programs etc. RBR was working properly, just after installing Simhub, the lag game has 8 fps.

Before I was shooting on a simbub version in early 2019, I had no problem.

Regards,

David

**Comment by SHWotever** [comment]
Hi ! 

Sorry for the long delay, I admit this is a mystery which kept me speechless :D . Could you you try to update to the latest version (6.9.1) there have been some reports of WMI overconsumption when simhub was running which could explain such situation.

Could you confirm me one thing, because I'm not sure if it was a bad simply a typo. Does RBR still lag when SimHub is not running? 

Nicolas

**Comment by OneDadz** [comment]
Hi!,

no problem.

no problem.

So I have a very good news, thanks to the update of SimHub, I was able to identify the problem.

I have a Corsair wireless keyboard, I just unplugged the usb, and the RBR game works fine :).

[SimHub.log](https://github.com/SHWotever/SimHub/files/3900631/SimHub.log)


David

**Comment by SHWotever** [comment]
Ah indeed, corsair keyboards are known to cause some weird issues (not specifically due to simhub thought), i think it's related to their high refresh rate mode, on mine, there is a switch to choose the working mode, I switched to the regular mode I never had any issues since.

**Comment by OneDadz** [comment]
ok thank you, I'll see if I have a setting like that.
