### ISSUE TITLE
F1 2019 Fuel Calculations wrong?

### ISSUE THREAD

**Issue by mihi4** [SHWotever/SimHub#452]
It looks like DataCorePlugin.Computed.Fuel_RemainingLaps doesn't work in F1 2019 correctly.

i.e. I have 3 laps to go, 9L left (of 110), Usage is 1.8L/Lap - Remaining Laps starts to get negative(how is this possible in dividing positive numbers?) and lowers more and more, down to -2.something.... But 9/1.8 is 5, not -0.6 ;)

DataCorePlugin.GameRawData.PlayerCarStatusData.m_fuelInTank looks correct, DataCorePlugin.GameData.NewData.RemainingLaps too, DataCorePlugin.Computed.Fuel_LitersPerLap is mor or less constant.
DataCorePlugin.GameRawData.PlayerCarStatusData.m_fuelInTank is the same as DataCorePlugin.GameData.NewData.Fuel

So the data seems correct, but the calculation seems to use the wrong data to calculate.

Interestingly, also DataCorePlugin.GameRawData.PlayerCarStatusData.m_fuelRemainingLaps shows some strange values, it's oscillating between 1.02 and 0.98 up and down...

SimHub version 6.9.1 (just downloaded 5min ago)

greetings
michi

**Comment by SHWotever** [comment]
Hi ! The data is matching the on dash display

It looks a bit weird compared to other games with more basic computations, 
Basically DataCorePlugin.GameRawData.PlayerCarStatusData.m_fuelRemainingLaps gives how many laps will be remaining after you complete all the laps, so negative values means you will lack fuel to complete them, and positive means you have excess.

This data is used to compute a matching "remaining laps" (in DataCorePlugin.Computed.Fuel_RemainingLaps) basically it computes how many laps to go (in float way : ie 1.3 laps remaining to do ) and add this to the game value to get the "game" estimate of how many fuel laps are remaining in total. Since the game data is totally out of my control it could be negative in some circumstances, but most of the time it's fine.

**Comment by mihi4** [comment]
Thx a lot for your explanation. Looks like an incoming bugreport to Codemasters ;)

greetings
michi
