### ISSUE TITLE
Toggle mute Button 

### ISSUE THREAD

**Issue by nrg1991** [SHWotever/SimHub#465]
The toggle mute Button (selected Button) for static wind in the Shake it Section is clear (Deleted)  If SimHub starts the next time.

By the way can someone explain how the option „toggle when Pedal reaches %“ exactly behave on the specific effect?

Thank you! And thank you so much for this useful tool!!!! I love it!

**Comment by SHWotever** [comment]
Hi not persisting mute was intentional, I made a difference between "disabled" (which is persisted) or muted (which is not) I made this to avoid manipulation errors like unwanted muted effects. I will look to add an option to leave choice about this behavior.

About  „toggle when Pedal reaches %“ it's a "filter", it will only allow the effect when you are at "X" percent of braking and/or throttle, otherwise, it won't output anything. this allows to optionally focus only on braking/accelerating

**Comment by SHWotever** [comment]
Hello ! I've added the option for the next release : 
![image](https://user-images.githubusercontent.com/2207331/72187770-dc59cc80-33f8-11ea-929d-e85c447ea359.png)

**Comment by nrg1991** [comment]
I think there‘s a mistake in my Description of the Problem.. I‘ll try to explain it again.. sorry for my bad english 


Gesendet von Yahoo Mail für iPhone


Am Freitag, Januar 10, 2020, 10:30 PM schrieb Wotever <notifications@github.com>:


Hello ! I've added the option for the next release :

**Comment by SHWotever** [comment]
Ah ! Sorry i misread it, I see indeed it's the control assignment which is not saved. I've fixed it.

Nicolas

**Comment by nrg1991** [comment]
Yes! That‘s it 😎 thank you man! And Thank you for the quick answers and this beautiful Software 😍 is there any plan for a abs effect for motors or Shakers? For example in assetto Corsa competizione the Motor on the brake Pedal only works with abs off because of Wheel lock. The shakers do something when abs kicks in.. I think because the wheelVibration or something.🤔 
Best regards and keep up the good work 👌🏻🙏🏻


Gesendet von Yahoo Mail für iPhone


Am Freitag, Januar 10, 2020, 11:06 PM schrieb Wotever <notifications@github.com>:


Ah ! Sorry i misread it, I see indeed it's the control assignment which is not saved. I've fixed it.

Nicolas
