### ISSUE TITLE
[Feature Request] Overlay layout - Back to front reordering

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#467]
Hi, it suggestion time again ;)
It think having the possibility to reorder elements in the overlay layout editor list, so that it impacts their foreground/background positions, would be helpful for overlapping overlays. Just like in the Dash Studio editor.
![image](https://user-images.githubusercontent.com/50543913/72208948-62355080-34a9-11ea-9c5e-d9623a3e3185.png)
Thanks for considering the idea.

**Comment by SHWotever** [comment]
Hi ! 
Unfortunately these are simply transparent windows, since they are always on top the ordering is managed exclusively by windows and I have no way to influence reliably the order. Since I've prevented windows to get focus when clicking on it it seems "not to change" but if somehow a window gets the focus (alt-tab, last open window ...) it will be put automatically by windows in front of the others. I'm afraid the only way is to avoid any overlapping. The only alternative solution was (in the past) to build a fullscreen transparent dash, but it was a big performance bottleneck.

**Comment by Romainrob** [comment]
Hi.
Too bad but I understand the limitations.
Alt-tabing while editing the the layout actually does the trick. :)
On a side note, once I've alt-tabbed to one of the overlays to bring it back on top, if I alt-tab again, I don't see it anymore. Which is a bit weird.
Thanks for your answers. :)
