### ISSUE TITLE
RF2 overlay oil and water temp not working

### ISSUE THREAD

**Issue by thomasvjohansen** [SHWotever/SimHub#471]
using any of these does not give more than a "0".

[DataCorePlugin.GameRawData.CurrentPlayerTelemetry.mEngineOilTemp]
[DataCorePlugin.GameData.NewData.OilTemperature]
[DataCorePlugin.GameData.NewData.WaterTemperature]

**Comment by SHWotever** [comment]
Hi ! This is happening on lot of recent mods (official) : detailled car characteristics and handling (slip, engine temps, tyres ....) are kept "secret" by the game.
This is due to a non disclosure agreement from the game development team with car manufacturer so these details are not available to the public.  

If you try older cars (avoid most gt3s), which are not under "non disclosure agreement" you will get these data

**Comment by thomasvjohansen** [comment]
Oh didnt know that, what a sad way manufactures are pushing sim games.
