### ISSUE TITLE
ACC arduino and "DELTA TO" function

### ISSUE THREAD

**Issue by lolo2306** [SHWotever/SimHub#472]
On Assetto Corsa Competizione, I use the leds (2812B with arduino mega) as indicators of winning or losing time but the leds display does not correspond at all to the indication given by ACC...
Where can I find documentation on "DELTA TO" function ? 
![image](https://user-images.githubusercontent.com/10076744/72680286-79cb9500-3ab8-11ea-92ad-17d3e85afd94.png)

**Comment by SHWotever** [comment]
Hi ! 

The game does not give that data (like most games unfortunately) so it's computed by simhub based on a "gps-like" lap comparison (based on laps recorded by simhub). Since the ingame computation method is not known unfortunately I can't reproduce it exactly, that's why you will see some differences between in-game and simhub display.

Nicolas

**Comment by lolo2306** [comment]
Thank you for your response.

**Comment by SHWotever** [comment]
No problems ;)
