### ISSUE TITLE
Clearing session best ?

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#481]
Bonjour,
Is there a way to clear PersistantTrackerPlugin.SessionBest please ?
Clearing lap history seems to ignore it.
Bon dimanche.

**Comment by SHWotever** [comment]
Hi ! Clearing lap history will clear the data computed by simhub, but indeed when the session best is given by the game it will still be reported. It's the case on most games. Originally it was totally separate (game data and simhub tracked data) but after lot of complaints about that I tried to keep data in sync as much as I could, and only complete missing data with simhub tracked laps, that's why resetting laps will only reset that specific part. On iracing specifically if I correctly remember, session best and delta is given by the game, but nothing about all time best. So clearing lap history will only affect at best

**Comment by Romainrob** [comment]
I see. This makes sense.
I was asking because during yesterday's team event, the displayed session best was the best lap of my team mate. Telemetry gets weird with when driving as a team.
During the next team event, I'll dig through the available data to see if I can find a workaround...
or get slower team mates. 
Thanks for your quick answer :)
Bonne fin de journée.
