### ISSUE TITLE
[Feature Request] Evochron Legacy -- Text file telemetry to SimHub?

### ISSUE THREAD

**Issue by AppliedInsanity** [SHWotever/SimHub#488]
With all the amazing work done in extracting telemetry data from games without "easy" access to it, would it be possible to integrate data from sims like Evochron Legacy? The game exports 145+/- real-time values to a text file (!) in the game directory . I have been working on a multi-station simulator project based on EL (a two-seat fully simulated "spaceship" interior, more akin to a cargo plane than, say, an Artemis bridge) and this software is looking like the solution to all of the problems connecting displays and devices. I'm focusing on the physical structure and individual panels and associated hardware, and I keep coming back to the incredible amount of hardware support SimConnect has. 

Programming is not my strong suit, and to see the amazing setups and creative ideas on the site makes me anxious to see whether it's possible to use this software to integrate all of the hardware, LEDs and displays I have collected for the project. I have been looking for the means to link the data to hardware for years. Getting the data is trivial. Doing something with it... well that's problematic. 

Honestly, it seems simple, from a programming perspective, and yet I'm not a programmer and I'm not making much headway. Any advice or suggestions are welcome, as I'm trying to move the project forward. 

Thanks to all of you and the incredible amount of work you have put into this project, and for entertaining the question.

**Comment by SHWotever** [comment]
Hi ! 

This looks interesting, though I have huge doubts about "real time" and "text file". I bought the game but unfortunately I could not find this telemetry file. Do you have some articles or infos about that as a starting point ?

**Comment by AppliedInsanity** [comment]
https://www.starwraith.com/evochronlegacy/customkit/readme.htm

https://www.starwraith.com/forum/

The game looks in the root folder for a text file named
"savedatasettings.txt", which you create in Notepad or whatever.
Instructions for finding the folder in Steam are in the customization docs.
There's one line -- just the delay to write out the data, in milliseconds.
That's it. The game starts filling a file named "savedata.txt" in plain
text, a value per line, 144 variables or so, every whatever delay.  The
docs explain the type and purpose for each line/value. I had done a few
very basic scripts and apps that would display the data, but I could not
figure out how to run the lights and effects like this software does! I've
seen some amazing interactive displays and gauges integrated into a lot of
sims here, and I'd like to think I won't have to reinvent the wheel to
build this ridiculous project of mine:
madderlyslady.blogspot.com.

I appreciate your time and your responses. I've reached a point where i
feel like if I don't build this now, I never will. All (I think) I need for
control software is here - and I'd love to find a way to make it work.
Thanks for looking into it.

**Comment by bbenoist** [comment]
@SHWotever 

> though I have huge doubts about "real time" and "text file"

From what I remember of my cross-platform developer days, you're right to have doubts...
...on Windows. Because, AFAIK the OS writes directly on the disk which could be a very fast SSD however but could also be a 5400rpm hdd with a poor cache.

On Linux, it's different because, IIRC, the filesystem is cached in RAM so unless you're swapping or writing a lot of data at once, you should not suffer from latency or race-conditions.

@AppliedInsanity 

_From the docs of Starwraith documentation:_

> Inside the file needs to be an integer value to specify the update rate for the game to use in milliseconds. A good setting to start with is 5000, or 5 second updates

After reading this, my guess is that the feature is primarily used internally for debugging purposes (hence the 5 seconds refresh rate) and that someone at Starwraith thought that it would be a good idea to make it accessible from end-users 😉 It has not been designed for real-time stuff and that's the reason why the `telemetry` and `real-time` words are not even present in the documentation.

**Comment by AppliedInsanity** [comment]
Would I NEED "real time"?
The project I'm working on is to mimic the cockpit of a utility spacecraft.
I have a single-seat prototype frame built, and I'm designing panels and
hardware to support the inputs and flight controls. I have controls for
almost any conceivable function the sim supports.
As for the aesthetics, that's all me. No off-the-shelf panels, everything
is custom designed to LOOK as if it has function and purpose. I'm using
prop and set design techniques to build as realistic an environment as
possible. My hack job programming skills have gotten me to be able to light
a light or create a rough screen of data I can reference when flying. A
taste of success drove me to want the whole thing interactive. It's
literally smoke and mirrors, faking a space ship like they do in movies and
tv, and the intent is to be able to share that space with people that don't
play hard-core sims.Artemis and Objects in Space are clever approaches, but
I'm more Firely than Star Trek. Used and abused is what I'm going for, and
the point is to make it a shared environment that multiple people can enjoy
at one, running on the same sim.

Entering the atmosphere in-game?  I'll have Neopixel strips to light up the
space behind the monitors like re-entry. Incoming missile? I'll want
warning lights and a sound board. I'm creating a set piece or a huge prop
as much as I'm trying to faithfully recreate a real-time sim environment. I
can afford a second or two delay. I'm just trying to put my time and
resources into creating the props and environment without reinventing the
wheel coding the interface.

This is a ridiculous project, I admit. And one that I have spent thousands
of hours and thousands of dollars gathering materials and parts to make it
look as realistic as possible. I'm just trying to find a way to make it all
"live". I've looked over a number of software packages and SimHub has the
ability to drive nearly all of the hardware I've collected over the years.

I'm in the process of turning my 600+ pages of notes into a working
document, and a local maker space is helping me actually create the pieces
I'll be filling the space with. I guess I didn't realize that the telemetry
might be such a pain to incorporate. Thanks so much for looking into this,
and if I can be more clear on what my expectations are, I'll try to reach
out again.

**Comment by SHWotever** [comment]
Hi !

Sorry for the long wait, but this request always got me in dilemma, 
Reading telemetry through a text file overwritten again and again is the best way to kill a SSD, on another hand slowing down the write is totally out of the simhub philosophy, telemetry must be fast to be able to build effects, reactive displays etc ...
Due to these reasons I won't implement it except if a proper telemetry access is published.
I understand that it could be frustrating, but I don't want to add deceptive game implementations with low speed refresh, no shakeit feedback ... And lettting a SSD burn in a few days is not responsible neither.
