### ISSUE TITLE
Nextion Display via Arduino Nano?

### ISSUE THREAD

**Issue by MattG351** [SHWotever/SimHub#489]
Hi is it possible to run the Nextion 4.3" display off of a Arduino Nano? I tried to upload the sketch in the addons directory per the wiki but am meet with the following error:

Arduino: 1.6.13 (Windows 10), Board: "Arduino Nano, ATmega328"

In file included from C:\Program Files (x86)\SimHub\_Addons\NextionMicroBridge\NextionMicroBridge.ino:26:0:

C:\Program Files (x86)\SimHub\_Addons\Arduino\ArduinoIDE\arduino-1.6.13\libraries\Joystick\src/Joystick.h:32:2: error: #error The Joystick library can only be used with a USB MCU (e.g. Arduino Leonardo, Arduino Micro, etc.).

 #error The Joystick library can only be used with a USB MCU (e.g. Arduino Leonardo, Arduino Micro, etc.).

Any help is appreciated, I am fairly new to this.

**Comment by SHWotever** [comment]
Hi !

No it's not supported i'm sorry, you need an arduino micro for this purpose. Only the arduino micro has the required capabilities for efficient communication with the nextion.

You can read the two possible nextion wirings on the wiki : https://github.com/SHWotever/SimHub/wiki/Nextion-Display#nextion-wiring

In the specific case of the nextion the arduino is used as a ttl emulator, that's why it differs from all the other simhub arduino compatible hardware.
