### ISSUE TITLE
ETS2/ATS Map on SimHub Dashboard

### ISSUE THREAD

**Issue by HerrKnaeckebrot** [SHWotever/SimHub#502]
I'm working on my own Dashboard for ETS2 and ATS and tried to add the ETS2 Map from the Bar on the left.
Even if I run the Dashboard on Google Chrome, it doesn't show me the map, only the blue "truck arrow".. Is there anything i need to do making it work? 
I don't have that much experience, it's my first dashboard..
Hope someone can help me out, thanks!

**Comment by sjdawson** [comment]
Hey @HerrKnaeckebrot, if you're seeing the blue truck arrow, then it at least shows that the map component is loading - it'll only work when loaded from a web browser, such as Chrome anyway, so windowed mode won't work.

Are you playing with any mods installed in ETS2 that modify the map (new cities ets)? IIRC, the map in SimHub only supports the base game, so that could be the reason you're only seeing the blue truck symbol and no other info.

**Comment by SHWotever** [comment]
Closed due to no feedback.

Thanks @sjdawson it's likely to be the cause indeed.

**Comment by ptitdiable17** [comment]
salut @HerrKnaeckebrot  a tu reussi?
