### ISSUE TITLE
Strange led Error

### ISSUE THREAD

**Issue by basthard300** [SHWotever/SimHub#510]
I connected my Arduino NANO v3 (ATmega328)
and from today, with 24 LEDs connected systematically, the LEDs from 17 to 24 no longer light up, what can I do ??
from my friend it works (win7), from me not no !!! however it was always gone.I have Windows 10 latest update.
what happens?
Basthard

**Comment by SHWotever** [comment]
Hi ! Since it's only 17 to 24 it matches a full led strip, in this case my first guess would be a weak soldering, since when moving it on another computer it worked I would really check solders cautiously as it may be sneaky.

On another hand it could be simply a configuration issue, do not hesitate to check in the simhub preview if the whole 24 LEDs are lighting up. 

Windows update will not have any effects on a single led strip, no worries about this ;)

You can also check the hardware using the process available on the wiki (lighting all leds in red at sketch setup


Let me know if it helped, 
Nicolas

**Comment by SHWotever** [comment]
Soe useful links :
https://github.com/SHWotever/SimHub/wiki/Arduino--Setup#soldering
https://github.com/SHWotever/SimHub/wiki/Arduino-WS2812b-RGBLEDS--Wiring-Setup#testing-your-leds
https://github.com/SHWotever/SimHub/wiki/LED-Editor-guide

**Comment by basthard300** [comment]
hi, in the meantime I solved it,
even if I can't understand why if Arduino goes through a 3-port USB Hub when writing the firmware, you lose something ... anyway I think I have solved it ... thanks for the answer !!!

**Comment by basthard300** [comment]
I will try to change HUB if it does again ...
Thanks for your assistance
Paul
