### ISSUE TITLE
Turn indicators left and right ... and others

### ISSUE THREAD

**Issue by JemmUA** [SHWotever/SimHub#525]
Hello. I have some truobles:

1. The left and right turn indicators for Assetto Corsa Comptezione do not work.
[DataCorePlugin.GameData.NewData.TurnIndicatorLeft] and [DataCorePlugin.GameData.NewData.TurnIndicatorRight] 
are always Zero

2. SimHub does not start with windows - only manualy. 

3. Pressed button before first pressing returns [null] , after pressing 0 and 1. And [null] is as Enabled, like button is pressed.
Demo here: https://www.dropbox.com/s/z36x5bp3qx6x858/buttonBug.gif?dl=0

**Comment by SHWotever** [comment]
Hi ! 
TurnIndicatorLeft and TurnIndicatorright are unfortunately not supported in AC since it's not available in telemetry you can see the status of each data here :
![image](https://user-images.githubusercontent.com/2207331/78673971-2e6c9a00-78e3-11ea-979e-8caee60df07f.png)

About input status indeed button is not known before the press, handle properly null you simply needs to wrap it with isnull (second parameter is the dafault value when its null  : 
isnull([InputStatus.JoystickPlugin.Controller_(XBOX_360_For_Windows)_B00],0)

About windows start could you give me the logs after a windows startup so I can see what is happening? (Logs are stored in C:\Program Files (x86)\SimHub\logs)

**Comment by JemmUA** [comment]
May be this is the reason, but the simhab is not installed on the C: drive, but here
G:\Utilites\SimHub
https://www.dropbox.com/s/zbq0hpjk5xkay5w/Logs.rar?dl=0

**Comment by SHWotever** [comment]
Thanks for the logs, I could not see any particular errors,

Could you check here that startup is still enabled ? If you disabled it from task manager Simhub won't detect it and still think auto-startup is active. If it's disabled you can simply right click and enable it
![image](https://user-images.githubusercontent.com/2207331/78696899-59191b80-7900-11ea-802b-39a62031886c.png)

**Comment by JemmUA** [comment]
I did it, but without reasault. 
Now i made clean setup, And it helped!
Sorry for disturbing and big thank You for help!!!

And one more question.
Is it possible to make any variables to save data for calculations (for exampe fuel for time)?
