### ISSUE TITLE
Dash Studio - No text wrapping in HTML mode

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#529]
Hi,
I'm having an issue with text wrapping. It won't work in HTML mode. It's fine in desktop mode.
![image](https://user-images.githubusercontent.com/50543913/79384048-84d27c00-7f66-11ea-88ce-328fd8d96231.png).
Is that expected?
Bonne soirée.

**Comment by SHWotever** [comment]
Hi !

Indeed it's a known limitation (probably just by me and you now :D) due to the difference between WPF and HTML, I can't break words exactly as WPF can, however it will wrap after any spaces.

I took an additional look, there is a "break-word" word-wrap which exists in CSS and would be closer to WPF, but due to the required HTML structure to ensure to get a vertical and horizontal alignment as close as possible to WPF, it won't work in this specific situation, unfortunately.

**Comment by Romainrob** [comment]
Don't worry Ill keep the secret safe :)
I just tested using a space between characters. I does mess a bit with the horizontal alignment but I think it will do the trick as it looks the same in desktop and HTML mode.
Thank you for the quick answer!
