### ISSUE TITLE
Golf 3 Instrument cluster problem with simhub.

### ISSUE THREAD

**Issue by jaxxident** [SHWotever/SimHub#533]
Hello. I have a little problem with my golf 3 instrument cluster and arduino. So I hooked everything up, but it seems that fuel and temp gauge don't work correctly. They only have 2 positions: max or zero. If the fuel tank is full in game (beamng) the gauge will go max and if its let's say half a tank the gauge will go to zero. There's no inbetween. Also I didn't get the speedo to work, should be the same as E36 cluster tho. I know that RPM gauge needs additional 12v. I'm using arduino mega and I wired everything up by this picture https://www.sim-pc.de/wp-content/uploads/2017/01/Golf3_schematik.jpg

**Comment by SHWotever** [comment]
Hi ! Unfortunately I have no knowledge about other clusters signal requirements that's why I can't give support for these and I only kept focused on a single known cluster.

What I can say is that in simhub fuel and temp signals are simply pwm signals (0-5v) while Speedo and tachometer are half-dudy cycle pulse signal. You need also to make sure to follow the specific pinout available in documentation, otherwise the pwm gauges will not work. E36 accepts pwm signals but it's not a common thing around : fuel and temp gauges on more classic conditions are variable resistors between the gauge sender pin and the gnd, it's maybe the kind of signal expected by your cluster which is not compatible with the e36 support.

**Comment by jaxxident** [comment]
So simhub only supports e36? Another strange thing that I discovered: when I unplug arduino from pc (usb) the gauges will go to random place, water temp in the middle and fuel below half tank for example. Is it possible that there is some kind of electrical problem with arduino?

**Comment by SHWotever** [comment]
Hi ! Indeed it's the only one I support, mainly because it's impossible to know and support all the various clusters which exist :D, Even professional car workshops don't have this knowledge I guess :D 
Concerning the position when arduino is unplugged, since there is no signal anymore, I guess that explains that random position, Does your arduino gnd and powersource gnd are connected together? It may feels like a broken gnd situation.

**Comment by jaxxident** [comment]
Yes I have a wire from 12v power source ground to arduino ground pin under "power" section. Should I put it to GND in "PWM" section? Of course I get it that it's impossible to know all the instrument clusters, I just found out that Golf 3 is very similar to E36 and my friend had one over so I decided to give it a try. If I don't get it to work I will find e36 cluster anyway :D Thanks for the answers too!

**Comment by SHWotever** [comment]
So your gnd is ok, all gnd pins of the arduino are tied together, only connecting to the power gnd pin is enough.

**Comment by jaxxident** [comment]
Okay I just discovered another interesting thing. As soon as I disconnect gnd from arduino, tacho and speedo start to wobble around randomly. As soon as I connect gnd back they will go to zero position and temp and fuel will start to work. If the gnd is disconnected fuel and temp don't work :D

**Comment by jaxxident** [comment]
Okay tacho and speedo still don't want to cooperate some times :D One works but the other doesn't and they affect eachother pretty badly

**Comment by SHWotever** [comment]
Hi ! I close the issue as this cluster in unsupported and I'm not of any help here.
