### ISSUE TITLE
PCars2 UDP for consoles

### ISSUE THREAD

**Issue by negativeone90** [SHWotever/SimHub#543]
Great job on adding UDP support for consoles!

One question: PCars2 supports two formats for UDP – both PCars1 and PCars2. Will SimHub support older protocol for UDP? Some other 3rd party apps use only PCars1 UDP protocol, thus using them together with SimHub at the moment is impossible. For instance, CrewChief only supports PCars1 UDP protocol for consoles, so I can only use SimHub for bassshaker (with PCars2 UDP) or CrewChief for spotter (with PCars1 UDP) – but not both of them simultaneously.

I'd appreciate a response!

**Comment by SHWotever** [comment]
Hi ! 

Simhub is mainly focused on PC, however PCars2 was requested a lot that's why I made an exception with a new game reader only dedicated to consoles.

But each new game reader requires a lot of maintenance work later to test it and make it support all the future features (not counting the initial development time). Due to that, I don't plan to add support for PC1 API for now (probably for the same reasons crew chief did not add PC2 API).  I may change my position later, but for now, as I'm the only developer behind the scenes and doing it in my free time I have to choose wisely what to work on, and I want to stay focused on bringing new features to windows compatible games.

Nicolas

**Comment by negativeone90** [comment]
Thank you for a reply, @SHWotever – it makes perfect sense! From what I've been seeing so far in lots of forums about PCars2, it looks like their approach to API documentation is far from perfect, and the API itself is pretty shabby and buggy.

Either way, I get your point 100%, it wouldn't make that much sense to create a feature for such a small audience (as I am almost sure that the case I described is way too rare to put lots of dev effort into supporting it). Guess I better hope they (SMS) do a better job supporting 3rd party app developers with PCars3 (whatever it's gonna be called).

Appreciate your timely response, and thank you for the great work you're doing with SimHub!

**Comment by SHWotever** [comment]
What' you've been seeing to totally true. Adding pc2 UDP has been a really painful experience to be totally honest :D. I had to spread out the development over months due to the unusual quantity of anomalies, strange things, and difficulties occurring with the UDP API.

I don't totally exclude adding pc1 UDP in the future but for now I need to recover from PC2 injuries :D
