### ISSUE TITLE
MonitorSleep - Crash

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#544]
Hi,
Out of curiosity I tried the MonitorSleep event target.
After pressing the trigger action now button, my screens go black for an instant then It's seems to constantly hang SimHub on my system. I have to kill it at this point.
I don't really plan on using this feature but I thought you might get some info out of this.
Here are the logs file
[SimHub.log](https://github.com/SHWotever/SimHub/files/4536642/SimHub.log)
Bonne fin de soirée.

**Comment by SHWotever** [comment]
Hi ! Thanks for the feedback, I did not got it during my testings, but I could reproduce it instantly when debugger was not attached. I will remove it as it was really a side feature I copied from another project (simdeck) but I can't see why it can't work in this condition and since it goes straight in a windows call I don't have any margin to understand the crash and fix it  :( .
