### ISSUE TITLE
TM 1637 configuration information

### ISSUE THREAD

**Issue by EBEALIEN** [SHWotever/SimHub#563]
Good morning everyone and a wish you are all well!
I would like to include in my dash, in addition to the matrix 7219 and the TM1638 module and various RGB LEDs, which already works, also a 4-digit TM1637, but I don't know how to configure it for speed or anything else.
I don't want to mess up the working configuration.
Thanks
_google tralation sorry_

**Comment by SHWotever** [comment]
Hello !

The tm1637 will be your second text module so you need to put some content in it :
![image](https://user-images.githubusercontent.com/2207331/81262373-08e7c300-903e-11ea-860e-551b88e2cac0.png)

Simply double click on the screen to edit it, then choose the second module and added anything you need : 
![image](https://user-images.githubusercontent.com/2207331/81262473-36cd0780-903e-11ea-8140-b556c5b2af4a.png)

**Comment by ludop1** [comment]
Hi! i'm currently working on my wheel and I wanted to add the tm1327 modue as well, i am worried that i purchased the clock version  (if im not wrong is the one with the ":" in the middle), which i read is not supported.
I have watched a bunch of yt videos and many show that in fact a clock version used. 
My question is:
      is it possible to use the clock version in the first place?
and second of all, as reported by @EBEALIEN, is the tm1637 always in the second screen or is it just in his specific case?( because he already has a tm1638)

thank you very much for any answer in advance

**Comment by SHWotever** [comment]
Hi ! 

Clock version is really not recommanded as you won't get any decimal places, it really reduces the possibilites and dots will randomly appear as clock separator (:) but indeed overall it might work. Just a bit random and limited ;)

The screen numbering indeed depends of how many modules you have, if you just have a tm1637 it will be the first one, it takes it in order based on the type :
- all tm1638
- all tm1637 ....
