### ISSUE TITLE
Simhub hangs at 20% CPU usage when launching Dirt Rally 2

### ISSUE THREAD

**Issue by HoiHman** [SHWotever/SimHub#572]
When Dirt Rally is set as active game in simhub, simhub crashes when Dirt Rally 2 is launched.

Up on restart Simhub will hang and not start again until Dirt Rally 2 is removed from the user config as "current active game"  

Eventhough simhub is correct entered in the codemasters hardwaresetting.info, i keep getting the message that the game is not correctly configured.

Port is set to 20779 because 20777 and 20778 are used by my motion software.

If i disable automatic game detection and set Dirt Rally 1 as active game, i have no issues at all

[logs.zip](https://github.com/SHWotever/SimHub/files/4626467/logs.zip)

**Comment by SHWotever** [comment]
Hi !

Could you send me all the content of C:\Program Files (x86)\SimHub\PluginsData ? It contains all the settings in order to reproduce it.

Does it happens when all the secondary Softwares are closed ? I see many udp outputs being configured and active, so I guess you use other apps.

Let me know, Nicolas

**Comment by HoiHman** [comment]
Hi Nicolas, 

First of all thanks very much for your fast reply. 
I think i have managed to solve it.  I copied the entire simhub folder, uninstalled simhub, completely deleted the entire simhub folder and my config. Then i copied my dashboards back in from the backup and reloaded my license

I did have to re-set everything in simhub, but i looks like everything is working again.  
Strange thing was that it was "spreading" to Dirt Rally (1) to  :)

May i ask you also a different question?

Is it possible to have simhub support for F1 2019 (legacy mode) 

As you already noticed, i have a lot of motion software running:  SFX100, Simcommander 4 and Simhub.  Right now there's no full support for the new F12019 telemetry out put in SFX100 and SC4.
That why i'm using legacy, but that breaks simhub support again.

It would be great if this is possible somehow.

Thanks 

Henk

**Comment by SHWotever** [comment]
Hi !

Strange, happy that it's solved .

About legacy mode you can disable auto detect and use F12016. Legacy mode is really an archaic working mode which is coming from the old ages of F1 2012 or even older !  

Most of these apps ask for a fairly high price and keeping up to date does not feel like an excessive expectation. Simtools asks about 20€ a year to get access to plugin updates, Simvibe is more than 90€ for a license (same basis as simcommander, I don't know the price of the latter). I don't know about SFX100 but it is a more recent software and I'm surprised that it's still running on old api.

If somehow I get this request in a recurring manner I will consider adding the legacy mode, but to be totally transparent the idea of "downgrading"  SimHub because some applications do not go forward hurts me  ;)

Nicolas
