### ISSUE TITLE
[feature request] usb Xbox / Ps Controller support for shake it motors

### ISSUE THREAD

**Issue by gamefreak291** [SHWotever/SimHub#575]
just curious. the shake it motor ouput options require me to purchase a aduino board and usb shield to operate xbox stepper motors.

that being said isnt the PC capable of reading and picking up the whole controller itself to operate them? like the rumble test option in ds4 windows and remote playing.

i would like to just power my controller with a usb hub (external power source) and use a whole controller and just reroute the stepper motors with wires to my pedals totally eliminating purchasing anything except for clamps.

just curious if this is a liscense issue or if there was a way to repurpose the hardware the controller comes with originally vs only grabbing the motors and spending 60+$ to hook it up to simhub. maybe there is a way to do this and im missing it. 

thanks

**Comment by SHWotever** [comment]
Hi !

Actually there is a major difference between Arduino + motors, and controllers, the controllers runs the motors at 3.3v, while on Arduino 12v is suggested which makes then way stronger and reduces a lot latency.

On another hand, "software wise" I totally agree it would be possible to drive the controllers directly, however it can cause many issues, vibration motors are controlled through the force feedback, which means taking exclusive control of the controllers and potentially cause game conflicts. There are also issues with xbox one controllers not working when the application driving it doesn't have the focus. These issues combined with the power and responsiveness keep me away from adding this since the early days of shakeit. 

About budget do not hesitate to look on AliExpress and similar websites, well sourced you can do it for about 20$ and even less if you recycle the motors and or the power source.
