### ISSUE TITLE
Display LCD 20X4

### ISSUE THREAD

**Issue by 7HUND3R36** [SHWotever/SimHub#577]
Only in this section of simhub can I configure what I want to be shown on the 20X4 LCD screen?

https://i.gyazo.com/d7decc2ad78dd0199bbfb3b4b8585034.png

**Comment by 7HUND3R36** [comment]
I have another question, what is shown on the 20X4 LCD is very slow. For example, when it shows me the time the seconds go 2 by 2.

**Comment by SHWotever** [comment]
Hello ! Yes it's where its configured. About refresh speed indeed the hardware can refresh at a maximum speed of 7fps (due to I2C) faster would be unreadable anyway ;)

You can control how many lines are refreshed at once using this setting, If you use a single arduino with other displays by reducing the lcd refresh speed you will reduce the latency impact of other components :
![image](https://user-images.githubusercontent.com/2207331/82377821-8b9c5500-9a24-11ea-880a-1ef46c560c48.png)

**Comment by 7HUND3R36** [comment]
I leave you a video demonstrating.


https://youtu.be/e4rVqFeTSPs
