### ISSUE TITLE
Function "isincreasing" delivers true instead of false

### ISSUE THREAD

**Issue by xyz4tech** [SHWotever/SimHub#612]
The function "isincreasing" delivers true in situations where the value is slightly decreasing.

Example:
isincreasing(250,[DataCorePlugin.GameData.NewData.DeltaToSessionBest])

After a corner with a good exit there is a time advantage on the straight with just some hundredth of a second along the complete straight. The function "isincreasing" should deliver false but delivers true.

If there is a bigger time advantage the function works well.

**Comment by Romainrob** [comment]
Hi.
I guess the delta is wiggling around a little. Maybe due to computation margins or around the shift points.
You could try something like this to smooth things out:

isincreasing(250,
(
maximum(251,[DataCorePlugin.GameData.NewData.DeltaToSessionBest])
-
minimum(250,[DataCorePlugin.GameData.NewData.DeltaToSessionBest])
>
0.05
)
)

**Comment by SHWotever** [comment]
Hi ! Indeed the value is high precision and decimals will always oscillate a little,

**Comment by xyz4tech** [comment]
The observations I did showed that it isn‘t an issue with oscillating numbers. It‘s an issue with slightly increasing or decreasing values on the functions isincreasing() and isdecreasing(). In this situations the functions are delivering the wrong results.

Unfortunatly I don‘t know how to show you the behavior. Is there an log functionality which can be activated?
