### ISSUE TITLE
Right stick doesn't work in Project Cars 2

### ISSUE THREAD

**Issue by albertoarcagni** [SHWotever/SimHub#624]
When SimHub works in the background in my PC, the right stick of my controller (XBox360 connected to the PC through a USB cable) doesn't work Project Cars 2.
I tried to disable almost all the plugins leaving active only the controller input, dash studio, and the keyboard input but without a solution. I also tried to disable the controller input.

**Comment by SHWotever** [comment]
Hi !

That's really strange, I never had such feedback, when the controller input plugin is disabled do you still have the issue ? Simhub only reads the controllers status in this plugin (to be able to map buttons within simhub). could you try and tell me how it goes ? If it solves

**Comment by albertoarcagni** [comment]
Hi!

I confirm that the right stick doesn't work even if I disable the controller and keyboard plugins. To be sure I disabled the plugins, then I restarted SimHub then I launched PC2.

I've made also some other tests and I found that the problem is due to the fact that I run SimHub before PC2. If I run PC2, then I go to the desktop to run SimHub and go back to PC2 everything works (also with the controller and keyboard plugins). This is just a trick but it can suggest to you where the problem is.

**Comment by albertoarcagni** [comment]
I've just posted in the PC2 support forum
http://forum.projectcarsgame.com/showthread.php?68531-Right-stick-doesn-t-work-in-Project-Cars-2-when-an-external-app-is-running&p=1599504

**Comment by SHWotever** [comment]
Hi !

I investigated and I found that the issue was only occurring when starting the game using simhub launcher, when started from steam or a desktop link the issue was not occurring, this proves me that it's something occurring inside pc2, however after some additional search I've been able to find a workaround, if you set the game exe path as a startup action the bug won't occur anymore and the joystick will work, at least on my end : 
![image](https://user-images.githubusercontent.com/2207331/89444648-4f8aad80-d752-11ea-9e0b-3fb3379c04e1.png)

**Comment by albertoarcagni** [comment]
You are right, I have the problem when I run  PC2 from the steam icon in the application bar, not from simhub, and the launcher selection does not appear. When I run the game from the steam library the launcher selection appears and maybe it is the one that solves the problem. Then, I tried setting the custom path in simhub, and everything works.
It is possible that the problem may be due to the steam icon and simhub is a solution.
Thanks!
