### ISSUE TITLE
Making aftermarker gauges with electronic sensor working 

### ISSUE THREAD

**Issue by cazzoo** [SHWotever/SimHub#629]
Hello,

I wonder if there are any plans to get aftermarker gauges working when they use electronic sensors instead of mechanical ones.
I already got lot of troubles to get my boost gauge working before leaving it aside and I figured out why it was not working, mainly due to the fact it was using electronic sensor.

Regards,

**Comment by SHWotever** [comment]
Hi ! 

No I don't plan any new support for gauges, existing features has been one of the most difficult to support over time, mostly due to the huge variety of hardware available (the code itself doesn't have particular issue or difficulties, only the hardware), due to that I won't dig further in this direction and keep focused on more reliable possibilities. 

Nicolas

**Comment by cazzoo** [comment]
Hi Nicolas,

Thank you for your reply. I fully understand this might be time consuming. Do you somehow need help for maintenance or so ?
I'll stick anyway with my current setup using mechanical sensors. even though they're using stepper (slow) motors. It's more than enough. I'll open another ticket because I noticed the range seems not to work as expected for tacho and water temp. Will let you know all in info in the other ticket.

Casimir
