### ISSUE TITLE
working curbs in assetto corsa,...

### ISSUE THREAD

**Issue by promise2die4** [SHWotever/SimHub#640]
I couldn't find it, so sorry if this already is asked or posted or what ever,..

but why is the curb function in ac not working,.. please make that feature workable,.. cause thats one feedback you need in simracing,..

loving the app so keep it up mate!

Cheers.

**Comment by SHWotever** [comment]
Hi ! Unfortunately there is no dedicated telemetry channel available in the game data, that's why the effect is not available in AC. They recently added the data that acc but it's not giving the expected data neither. 
Currently we can only rely on suspension data but most curbs are modelled flat. Unfortunately I don't expect much new telemetry data as the game is already in a "end of life" cycle with no/little updates.

**Comment by promise2die4** [comment]
Aaaaah ok tnx for the fast reply...

Shame they dont deliver it cause ac is not on the end sol and csp is keeping it a live for life hahaha.

Anyway tnx, mate

**Comment by SHWotever** [comment]
No problems ;)

I agree the game is still alive with many mods etc.. but the reality shows that Kunos is mostly giving it's energy into acc updates, even if I would love to see some Improvements like new telemetry channels come to ac :D

**Comment by promise2die4** [comment]
Yeah thats true,... but we both know that will never happens unfortanatly...
