### ISSUE TITLE
Control to select Player name?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#647]
Can I make an interactive control to select (for example) a Player name (from a predefined list)?

I watched this video:

https://www.simhubdash.com/community-2/dashboard-templates/simhub-control-panel-a-dash-studio-overlay/

so the 'interactivity' seems possible.

I want to use this 'player select' later on to differentiate between different players "personal best times" and compare them with each other.

**Comment by SHWotever** [comment]
Hi ! 

This is another example of SDK usage, i don't know exactly how it's made in this particular case but using sdk you can create an action (which can be triggered by any input) and react to this like selecting a player and exposing properties related to this selection and finally using them in a dash.

**Comment by Shaftoe62** [comment]
Yeah, seems the SDK can't be avoided for what I want...

**Comment by SHWotever** [comment]
ncalc or js is implemented for simple computations, for everything more complex the sdk provides more flexibility and resusability.              And moreover it's more performant. Pushing further on ncalc or js would not have sense because it would be reinventing the wheel, c# (through the SDK) is well documented on the microsoft website, it allows to any kind of things (store files, clipboard, variables, http, persistence ....)
Everything in simhub except game readers which are above in the "hierarchy", is build based on this sdk, there are some little restrictions about UI mostly to avoid breaking the core of Simhub UI, but nothing really restrictive in term of possibilities.

**Comment by Shaftoe62** [comment]
Yes I understand, but I'm a bit reluctant to to go down that road because I will need to learn yet another programming language for only this purpose.

On the other hand I'm so dissatisfied with Codemasters Racenet and the impossibility to clear 'personal bests' from my account that I really want to have an alternative way to store that kind of information.

Not just for Dirt Rally but the same goes for everything Codemasters. And not only Codemasters either.

It's mainly because I often have friends over at my place to play on my rig and that muddies everything because they play on my racenet/steam account. Which also makes it impossible to compare times between us.
