### ISSUE TITLE
Too many questions or project abandoned?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#660]
Am I asking too many questions or is this project abandoned?

**Comment by SHWotever** [comment]
Hello ! 

The project is far from abandoned, since i'm the only one to answer, handle tickets, develop, troubleshoot and make evolutions and i'm doing it on my free time,I'm working on it pretty much every single day for 5 years :D, but I have to prioritize bug reports first, features requests get handled later or much later depending of my roadmap and feasibility ;) If I take the example of ghosts it's doable, but it will be the kind of evolution which will come in a few years if I get other requests. 

And indeed I've slowed down my answers to you a little because I've seen that you were able to find most of the answers by yourself and I needed time to finish the next simhub release. I try to answer to everyone but indeed I can't dedicate all this time to exclusively answer questions. It's indeed the disease of lot of small developer team (and on simhub i'm alone on my free time :) ) often the project will stall due to too many questions (mail, github, discord, facebook, various forums), I try not to "die" in this situation and that's why I'm "throttling" answers , to reserve some time to actually work on simhub code itself.

Currently I'm more in a "stabilization phase"  where I'm focused on improving existing features, more than adding new one, that's why despite numerous requests I won't add FS2020 for instance, this is not the current "target" of simhub, and adding flight sims needs lots of new features to come along. Obviously if something is a popular request and follow my current target I will work on it, I'm not saying I won't add any new features :D, I don't close features requests when they make sense which could appear as a dying project seen from github, maybe I should simply close it when I see no popular interest in it instead of leaving then accumulating in github.

I hope you understand the situation, I don't want Simhub to be a black box project with no capability to talk with the developer, that would be really sad, but on another end I need to actually work on it which you probably know needs lots of time and concentration :D
