### ISSUE TITLE
Gain modulation setting missing

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#679]
Bonjour.
Something bad must have happened to the gain modulation setting. It's missing :
![image](https://user-images.githubusercontent.com/50543913/95755934-55969080-0ca5-11eb-8824-0f5adcda88c1.png)
Bonne journée.

**Comment by SHWotever** [comment]
Hello ! I removed that feature where the effects were mostly unnoticeable, originally I introduced to make it hold "landing" on dirt rally, Since I now introduced a dedicated effect which catchs it and allows to set a dedicated frequency with a good "pulse" effect this setting had no particular reasons to stay. I will remove the remaining header ;)

**Comment by Romainrob** [comment]
I see. This makes sense.
Thanks you for your answer.
Bonne soirée !

**Comment by Romainrob** [comment]
And... it's gone ;)

**Comment by SHWotever** [comment]
Thanks a lot for the feedback !
