### ISSUE TITLE
Wind Simulator without Arduino

### ISSUE THREAD

**Issue by carlosflores** [SHWotever/SimHub#687]
Hello, I'm new here so sorry if my question is too basic or stupid.
So I'm interested in building a Wind Simulator to keep me fresh during the racing and also add more immersion to the game.
I did some research and found a lot of cases and tutorials using Arduino.
So my question is, is it possible to build a wind simulator just by connecting one or more PWM fans directly to a controllable fan header in the PC motherboard and then control the speed of the fans using the telemetry from the game passing this directly to the fan header by software without using Arduino?
In theory I think this should be possible since there is software that can control the speed of the fans and there is also software to get the telemetry from the game, so I don't understand why Arduino is necessary.

Thank you very much for your help.

**Comment by SHWotever** [comment]
Hi !

Even if technically it's possible in some conditions, unfortunately it's the kind of knowledge I don't have, it requires low level code to get access to such control and an extensive knowledge of the various mother boards models and brands. 

And even with that knowledge it's not assured that you can control all of them, in the past years I had many motherboards which could not be controlled by "generic software" like fan speed, afterburner ..) and I had to use the manufacturer specific software to control it.  Due to that it's not really a viable way in my opinion. 

On another hand the Arduino is universal, cheap and does not requires to deal with all the manufacturers specificities.

Nicolas
