### ISSUE TITLE
How to use PressType.During (probably)

### ISSUE THREAD

**Issue by lukester1975** [SHWotever/SimHub#703]
Hello again

Sorry if I've missed this documented somewhere!

I'm trying to figure out how to use `PressType.During` and `ControlsEditor`. At least, I think I want `PressType.During` - I want to start doing something when a button is pressed, and stop when it's released, but don't really want have to use two `ControlsEditor` (one for `PressType.Pressed` and one for `PressType.Released`) with two separate actions.

UI wise I have it working fine:

![image](https://user-images.githubusercontent.com/9592489/99551341-a0e24400-29b3-11eb-84a8-b4260210f982.png)

Also, no problems setting `ActionName` on the control so I can use `PluginManager.AddAction` to get called when the button is pressed, but wonder how properly get notification when it's released - seems like there's just the action when the button is pressed.

I've got things working by doing something like the following, but I imagine I'm not really doing things the right way! Could you point me in the right direction?

Maybe I should use a different UI control to get out the button name, and I'd just use `pluginManager.InputTriggered` and watch for press/release events and avoid actions completely?

Last question: could you explain what the return value of `InputTriggeredDelegate` and `InputTriggeredExDelegate` do? Does returning false stop the walking of the chain of handlers or something?

Thanks in advance!

Luke.

<pre>
pluginManager.AddAction("MyActionName", GetType(),
    (pluginManager2, buttonName) =>
    {
        bool Released(string input)
        {
            if (input == buttonName)
            {
                pluginManager.InputReleased -= Released;

                // ... do what I want when button released ...
           }

           // What does the return value mean?
           return true;
        }

        pluginManager.InputReleased += Released;

        // ... do what I want when button pressed ...
    });
</pre>

**Comment by SHWotever** [comment]
Hi ! 

indeed the "during" actions were not documented in the sample : 
you need to add the action including the "start" and the "end" action :
For this you need to use this method :
AddAction<pluginType>(string actionName, Action<PluginManager, string> actionStart, Action<PluginManager, string> actionEnd = null, bool hidden = false)
And specify actionStart (which will be triggered when pressed) and actionEnd (which will be triggered when released)
By using this you will be able to handle the "start" of the press, and the "end" .

The "InputTriggeredDelegate" return value is a bool saying if the value has been handled by a subscriber and if true it cancels any mappings triggers bound to the input, most of the time you want it to return false otherwise it will stop the normal simhub working mode, "True" is used for the "control picker" in order to catch inputs and avoid it triggering any actions as long as the picker open.

**Comment by lukester1975** [comment]
Ah, perfect. Works great. Sorry I missed it - pretty obvious from looking at the various overloads, my bad...!

Looks like the `hidden` parameter controls whether the action is registered in the app so accessible by anything?

Thanks again (and for the very fast reply!).

**Comment by lukester1975** [comment]
Ooh and one more question if I could. Last for the day, honest.

Is it possible to limit `ControlsEditor` to just a particular `PressType`? Nothing other than `During` makes sense for my usage, so would be nice from a UX point of view!

Cheers

**Comment by SHWotever** [comment]
Hidden makes it hidden in all the lists, I use it mostly when renaming an action so the old name is defined as hidden, the new one as visible, it allows smooth transitions without losing existing mappings. 

Concerning the presstype restriction it's not available yet, i will take a little ok to add it in a future update.

**Comment by lukester1975** [comment]
OK cool, thanks.
