### ISSUE TITLE
[Feature Request] - Export replay data

### ISSUE THREAD

**Issue by DFC-Keith** [SHWotever/SimHub#706]
Had a good search and haven't found anything concrete as to whether this has been addressed.

The saved replay JSON file isn't clear text therefore create an option to view / download this data in its full clear text form.

many thanks
Keith

**Comment by SHWotever** [comment]
Hi ! Unfortunately it's not possible, the data is serialised in various formats depending of the game involved in order to simulate as best as possible the raw game data. The data is also mixed with screenshots and compressed to save space. Even if exporting it as JSON would be possible, the resulting file would be hard to use because it requires to reproduce each game data structure and eventually parsing In order to use the data (for instance iracing is half yaml, half dictionary) 
Exporting/logging data would be more the role of a telemetry analysis utility utility which is not the kind of features I've been digging yet in simhub.

**Comment by chiclaio** [comment]
By the way, what about show documentation of head json file each game, like f1 2020

**Comment by DFC-Keith** [comment]
Thanks for the prompt reply, I fully understand.  Great app, thanks for all the work you obviously put into it.  My hope was to just be able to query the json and extract a couple of the items of telemetry data and put in a spreadsheet, shame that it isn't possible.

As you state though, it isn't really the direction that you want this to go and I fully understand / respect that.   I might grab the info and log the replay data as it passes through your replay engine.  If you can see it you can log it, somehow.  Thanks again.
