### ISSUE TITLE
Read .log files with the readtextfile function?

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#741]
Hi.
I'd like to display the last few SimHub error(s) on dash.
Using JS I can read the log file content if I rename the SimHub.log to SimHub.txt.
But it seems the readtextfile function does not accept the .log extension.
Is this something you could please allow/unlock on your end or is it a JS limitation?
Bonne soirée! :)

**Comment by SHWotever** [comment]
Hello !

It's because log file is a bit special it's kept opened by simhub in write mode, and it prevents classic file read, in this case simhub keeps the last known value (which never exists in this case). This was intentionnal to avoid reading partial data and having data inconsistency issues if the file writing and file reading happens at the same time.

**Comment by Romainrob** [comment]
Hi,
I see. I thought this was some kind of extension filter.
Thanks for the clarification :)
