### ISSUE TITLE
Unusual request? Direct control of a 12v solenoid with Arduino Nano

### ISSUE THREAD

**Issue by basthard300** [SHWotever/SimHub#755]
Good morning,
my project is to simulate the ABS pump when it comes into operation with a certain plugin in Simhub
This function should start my electromagnet when the state of this plugin (DataCorePlugin.GameData.NewData.ABSActive) goes from inactive to active
the Mechanical part is not a problem, also because it is an experiment but I just wanted to know how to get 12v when the above written plugin goes into active state.
If anyone can help, thank you in advance.
I am attaching a drawing I found online, if it can be the right one to leave
Thank you
![SolCir01](https://user-images.githubusercontent.com/61467596/108589821-8e83f780-7360-11eb-8d29-29a999917dfa.png)

**Comment by SHWotever** [comment]
Hi ! indeed this looks like a typical tip120 wiring, but hard to say how it will behave with a selenoid, i never experimented this.

Nicolas

**Comment by basthard300** [comment]
sorry but, maybe I haven't explained myself well, what kind of interface in simhub should I use and with which sketch, do you have any advice?

**Comment by SHWotever** [comment]
Ah ok sorry,

Since it's an unsupported usage you have two possibilities : https://github.com/zegreatclan/SimHub/wiki/Custom-Arduino-hardware-support , this first one allows you to add your own code inside the simhub sketch. 

Or : https://github.com/SHWotever/SimHub/wiki#custom-serial-devices-support

The second option is simpler overall but you have to do the whole Arduino serial protocol yourself.
