### ISSUE TITLE
WS2812B LED strip limitation

### ISSUE THREAD

**Issue by benallansmith** [SHWotever/SimHub#763]
Thank you for all your hard work, and this is only a minor inconvenience however I'd like to report a potential bug.

It seems there may be a limit on the size allowed within the sketch for WS2812B LED strips. 

I have a 3m 60LED/m LED strip (180 LEDs total), however the end of the strip doesn't light up. I have tested the full strip with regular sketch files and general FastLED patterns.

It seems to max out at around 150 LEDs regardless of what I set in the sketch compile configuration or the RGB LED setup.

**Comment by SHWotever** [comment]
Hi yes it's a deliberate limit, too many LEDs would lead to big latency (all the data has to go through the serial port which has a limited bandwidth) :
https://github.com/SHWotever/SimHub/wiki/Arduino-WS2812b-RGBLEDS--Wiring-Setup#limitations

**Comment by benallansmith** [comment]
I see, thanks for the clarification.

The way I have it set up on my workstation, I use all 180 for general lighting but would only be look to use the last ~60 of the strip for rev lights when my sim rig is connected due to their placement.

Does the same sort of delay occur when you're targeting the end of the strip compared to attempting to utilize a full strip?

**Comment by SHWotever** [comment]
No the actual target does not matter, the whole strand has to be refreshed no matter the placement. Actually there are two latency sources : Serial communication (which is optimized as much as possible in order to send only "changes", but a simple blinking on the whole led strip would trigger a full redraw and the optimization won't have any effect. The second source is the physical refresh by itself no matter what you change all the leds have to be refreshed, it's not a problem by itself as it occurs quite fasty, but during this operation no serial data can be sent or data could be corrupted.  That's why I had to set this 150 limit, it's significantly below what the hardware could do, but it ensure a decent response time no matter what is being displayed.

**Comment by benallansmith** [comment]
Ah ok, that makes sense. Thanks again for clarification. I can modify my set up to split the LED strips through two controllers so the rev light strip is shorter 👍
