### ISSUE TITLE
NASCAR heat 5 update broke telemetry

### ISSUE THREAD

**Issue by DG-Racing** [SHWotever/SimHub#765]
My Bass shaker is working for ACC but not Nascar Heat 5.  During testing in Simhub for Nascar Heat 5 the bass shaker tests/works
properly.  But during game play doesnt work at all.

Any suggestion why?

Thanks in advance

**Comment by SHWotever** [comment]
Hi ! Thanks for the report, I gave a try and indeed the game received an update which broke telemetry. I will update try to it, I hope it's still possible (extracting telemetry on NASCAR heat is not "obvious" as the game doesn't offer official telemetry)

**Comment by SHWotever** [comment]
Hi ! The fix has been released !

**Comment by DG-Racing** [comment]
Sorry, but how/where do I find the fix for the telemetry for Nascar Heat 5 that was done?  If I open up the game configuration it says No telemetry settings required, just start the game and have fun.But the bass shaker effects still are not working for Nascar.Thanks for your help in advance 


-----Original Message-----

**Comment by SHWotever** [comment]
Hi ! The fix has been released in simhub 7.3.8 : https://www.simhubdash.com/download-2/ 
It has been tested with the official steam version. Actually the issue was linked to the plugin injection timing, latest update of the game loads way slower than it used to and the plugin was loaded too early. PS : it only works with official steam version, make sure to set simhub to run as administrator in the settings, it will avoid some game detection issues.

**Comment by DG-Racing** [comment]
Thank you for your help 


Sent from the all new AOL app for iOS


On Saturday, April 3, 2021, 4:18 PM, Wotever ***@***.***> wrote:




Hi ! The fix has been released in simhub 7.3.8 : https://www.simhubdash.com/download-2/
It has been tested with the official steam version. Actually the issue was linked to the plugin injection timing, latest update of the game loads way slower than it used to and the plugin was loaded too early. PS : it only works with official steam version, make sure to set simhub to run as administrator in the settings, it will avoid some game detection issues.
