### ISSUE TITLE
ACC Shared Memory - Incorrect input?

### ISSUE THREAD

**Issue by KrisV147** [SHWotever/SimHub#776]
I think found an issue? Graphics.cs under SimHub\ACSharedMemory.dll>ACSharedMemory.ACC.MMFModels contains "public int[] CarIDs", however the Kunos shared memory document has this as "carID" (no 's').

There are two dependancies if i remember rightly, both in ACCManager.cs for GD_CarCoordinates() and GD_Opponents()?

**Comment by SHWotever** [comment]
Hi ! The name actually doesn't matter only the structure itself. Carids was implemented in the early days even before the official Kunos documentation was released. But renaming it now would break any third party plugin making use of it (even if it's not recommended). And to be perfectly transparent since the name is not really important in this particular case I prefer to keep a plural which is more realistic in my opinion to what it contains.
