### ISSUE TITLE
Multipel Vocore screens? 

### ISSUE THREAD

**Issue by ZebbeBa** [SHWotever/SimHub#782]
Can i have two vocore screens connected and working?, now when the 5” vocore is to be releases ( that i just assume works 🤔)?

sorry if i asked the question in the wrong place.

**Comment by SHWotever** [comment]
Hi ! No it's not supported, vocore does not expose any unique id allowing to attach consistently to a specific screen. Simhub will display on the first one returned by the windows system (this can be inconsistent accross reboots, that's why an unique id is mandatory to push further in this direction.
