### ISSUE TITLE
Throttle stops working.

### ISSUE THREAD

**Issue by carlosisla28** [SHWotever/SimHub#784]
Hi wotever, agains it’s me, I’m on my second tlcm set, and it does the same. When I have the motors on, the throttle randomly stops registering input. What do you recommend me to try?

**Comment by SHWotever** [comment]
Hi !

That's really strange, it could be an emi issue or maybe a current loss (contact with frame or something) but unfortunately it's related to the pedals themselves, I don't know this particular model in details and I can't tell if there are potential weaknesses which could be triggered by the vibrations or motors (magnetic field, emi...) 
The best way is to check step by step what is causing the issue
- I would try first to unplug the motor to check that it's the motor itself which is causing the issue,
-  then unmount the motor and keep it away from the pedals but keep it plugged to see if the issue stop

I see that tlcm uses a load cell for brake, maybe it doesn't like getting "parasites" vibrations. Hard to say. I would try to lower significantly the maximum motor gain to see if it helps. Maybe changing the motor direction so it vibrates left and right instead of up/down could help. And probably come back to some more "reasonably" sized motors would help, yours are really big and it's maybe too much for the pedals.

I'm sorry I can't help much more about this, this is clearly a strange interaction between the motors and the pedals, this is not a software issue and only trial and error will allow you to understand in which conditions the motors are distributing the pedals.

**Comment by carlosisla28** [comment]
![82C25434-F66B-4DAC-957C-6ACC4A7F3B54](https://user-images.githubusercontent.com/81610277/113530032-a4edb780-958a-11eb-9599-b0d51278036f.jpeg)


Just mounted like the picture, the problem is gone. So it was the vibration itself the problem? Did you imagine  how i can keep on the pedal levers? They felt stronger that way 😅

**Comment by SHWotever** [comment]
Honestly like I said it's hard to say, it could be vibration or magnetic field induced by the motor, but it's happening in the pedals themselves so I can't really say.
Considering it would "disable" the pedal consistently I would leave it here indeed, something in these pedals does not like getting vibrations ;)
