### ISSUE TITLE
custom protocol help :)

### ISSUE THREAD

**Issue by Palmix64** [SHWotever/SimHub#789]
Hi again guys, today I've made the last try to use my normal LEDs with simhub, with custom protocol. I've made a sketch on the SHcustomprotocol.h, and it works in the debug because I can see the 0;1 for example when there is a yellow flag, but my led doesn't turn on. Here is my code, if someone could help me I will be very happy

[customprotocol.txt](https://github.com/SHWotever/SimHub/files/6277700/customprotocol.txt)

**Comment by Palmix64** [comment]
Read about custom arduino protocol here:
https://github.com/zegreatclan/SimHub/wiki/Custom-Arduino-Hardware-Support

========================= Custom Message ===============================
========================================================================

format(
if(isnull([DataCorePlugin.GameData.Flag_Green],0),1,0)
,0)
+';'+
format(
if(isnull([DataCorePlugin.GameData.Flag_Yellow],0),1,0)
,0)
=========================== SHCustomProtocol.h =========================
============ (Change the pin numbers to match your setup) ==============

#ifndef __SHCUSTOMPROTOCOL_H__
#define __SHCUSTOMPROTOCOL_H__

#include <Arduino.h>
class SHCustomProtocol {
private:

public:
		// Called when starting the arduino (setup method in main sketch)
        void setup()
        {
      pinMode(6, OUTPUT);
      pinMode(9, OUTPUT);
        }

        // Called when new data is coming from computer
        void read()
        {
		
		// Reads until the semicolon and converts it to integer
      int green = FlowSerialReadStringUntil(';').toInt();
      int yellow = FlowSerialReadStringUntil('\n').toInt();
      
    /*
		//Read the message back to Simhub for debug
      FlowSerialDebugPrintLn("green : " + String(green));
      FlowSerialDebugPrintLn("yellow : " + String(yellow)); 
    */  
      
      digitalWrite(6, green);
      digitalWrite(9, yellow);     
      }

        // Called once per arduino loop, timing can't be predicted,
        // but it's called between each command sent to the arduino
        void loop() {
        }

        // Called once between each byte read on arduino,
        // THIS IS A CRITICAL PATH :
        // AVOID ANY TIME CONSUMING ROUTINES !!!
        // PREFER READ OR LOOP METHOS AS MUCH AS POSSIBLE
        // AVOID ANY INTERRUPTS DISABLE (serial data would be lost!!!)
        void idle() {
        }
};

#endif

here is the code if you don't want to download it

**Comment by SHWotever** [comment]
Hi ! This looks fine. I see you added the debug values and I guess it's where you have seen the data back so it means communication is working as it should. 
So by elimination I would check the leds by themselves, instead of digitalWrite(6, green); could you try digitalWrite(6, HIGH); it should force the led to light up. If it does not light it could mean the resistor is not appropriate and/or the led fried, or maybe a polarity issue. To check further I would simply unplug it and check that there is 5v as it should using a voltmeter.

Nicolas

**Comment by Palmix64** [comment]
thanks, I try and I'll let you know

**Comment by Palmix64** [comment]
ok, I've tried and the led is not fried, because with a simple sketch (pinMode, digitalWrite) it works. But when I try to put a digitalWrite on the custom protocol nothing happen, no idea why. This is the procedure, maybe there is a mistake here. I go to the file SHcustomprotocol.h and I write my code there. So I upload the sketch into the board and then I go to the debug. I think the mistake is here, because if the code is right, and the led is fine...

**Comment by SHWotever** [comment]
Hi ! I tested on my arduino, using the code you provided (I checked both pin 6 and 9), and it worked as expected. 
I just changed the formula in order to do a quick test, I simply used a blinking code for both values :

```
format(
if(blink('t1',1000,true),1,0)
,'0')
+';'+
format(
if(blink('t2',1000,true),1,0)
,'0')
```

So if the arduino code works it remains the possibility that the pins are used by something else, could you make sure that any other features are not enabled inside the sketch (simply open the setup tool inmenu file click on restore defaults, then click on save sketch in the file menu, it will reset the sketch, then you can upload again.

**Comment by Palmix64** [comment]
yeah, I think the problem is the arduino. when I go to multiple arduino on the ports screen it says always the same things, in cycle: Hello (waiting for arduino boot), Hello (sending), unrecognized, and then restart writing this. next days I'll try with an original arduino (the one I'm using is a clone we use at school), maybe the problem is that clone board. Thank you very much for your help, I'll tell you if it will work.

**Comment by SHWotever** [comment]
Hi ! I'm not sure it's the arduino, connection loop can be either a physical issue (dead arduino) or software issue, something breaking communication in the sketch. If you have issues, I would simply make a copy of what you have, reinstall simhub to restore the original sketch and reupload. if it works it means it's not an arduino defect.

Nicolas

**Comment by Palmix64** [comment]
ok, simhub reinstalled but again connection loop, but the arduino works with the ide... now I try to upload simhub code by ide.

**Comment by Palmix64** [comment]
ok, I've uploaded the sketch by arduino ide, and it works!! Thank you very much for your time man, amazing job
