### ISSUE TITLE
"Toggle overlay visibility" issues

### ISSUE THREAD

**Issue by whismerhill** [SHWotever/SimHub#808]
1 : can't assign a keyboard key to it, seems like it accepts only my controller as input. That is unfortunate.
2 : "longpress" is basically forced on me, having a controller the number of available buttons is limited (which isn't a problem until 3 )
3 : aforementioned "longpress" works weirdly.
e.g. you have to know & memorize the exact timing of the "longpress" because if you press it for slightly too long
then you'll end up disabling the overlay & immediately re-enabling it

**Comment by SHWotever** [comment]
Hi ! Concerning keyboard you can enable it in the simhub settings/plugins, it's disabled by default in order to reduce antivirus false positives (often antiviruses does not like seeing an application watching for keystrokes)

Concerning long press you have two kinds, ShortPress and ShortPressWithoutAutoRepeat , the second one is the one you want ;)

**Comment by SHWotever** [comment]
![image](https://user-images.githubusercontent.com/2207331/116761313-8fe43700-aa17-11eb-8e6c-3019bf32b6cc.png)

**Comment by whismerhill** [comment]
alright thanks.
this software takes time getting used to, it's complex IMHO. 
I think it could definetely make use of a "wizard" at the start
example : asking the user a bunch of questions such as what hardware the user has, (disabling some of the plugins, I do NOT intend to get such as "shakeit" stuff, does help me by having a less cluttered UI)
