### ISSUE TITLE
Some Cloud Map files are damaged (Dirt Rally 1)

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#836]
Some Dirt Rally 1 Cloud map files are damaged somehow. 

I can open them with the SimHub mapviewer but Windows reads them as filesize 0 and I can't 'unzip' them. Not with winrar and not with PHP.

I've tried new downloads for all of them but the problem remains.

It concerns these files from my incomplete set of only 26 cloud maps:
9666.5-9666.5.shtl (Anadou Farmakas)
10805.24-10805.2392578125.shtl (Hammertstein)
11684.17-11684.169921875.shtl (Oberstein)

From DR2 DirtFish is the same but that was expected.

**Comment by SHWotever** [comment]
Hi ! 0 bytes maps are not damaged, it's just that it's not available yet due to lack of data ;) , and it's cached to avoid trying to redownload it again and again just like a regular map, 
Cloud map only retains high quality records (time consistency, accuracy, distance of the data points, speed, aggressiveness of the turns and more criterias, and unfortunately dr1 usage is way lower than dr2 making slower to build the full range of available maps. It's just a matter of waiting ;) those large maps are much more often rejected based on one of this criteria. It's perfectly normal, considering the large quantity of data to process across all games it has to be extremely strict, currently the lap database contains more than 200 000 laps (which has been by the various quality algorithms, way more if you count quality rejects), it's humanly impossible to review them all one by one, that's why the rejects are extremely stricts.

**Comment by Shaftoe62** [comment]
Yeah you allready explained the strictness of the algorithm. No problem there.

But how then can I open these files in the map viewer??? When I open them with the map viewer it shows the complete map.

Or does the mapviewer fall back on the local recordings somehow?

**Comment by SHWotever** [comment]
Currently I only have 68 maps ready on dr1 and 5more with some data but not enough.

**Comment by SHWotever** [comment]
Hum, no but the map viewer scans the whole folder and allows to navigate from file to file , I need to check how it handles this particular case but you are probably viewing another file.

**Comment by Shaftoe62** [comment]
Could you zip those 68 DR1 files for me? Would save me a lot of time.

**Comment by Shaftoe62** [comment]
And you're right. The map viewer opens another file when I doubleclick a zero-size map file. Didn't expect that.

**Comment by SHWotever** [comment]
Perfect,

Concerning the zip file, after a second though, I won't deliver it, it's changing every day, it's not intended to be mass extracted. If I open the doors of giving that full database, anyone could request the same at anytime, and it's not something I want to do regularly.
