### ISSUE TITLE
Max7221 led matrix problema

### ISSUE THREAD

**Issue by DAPULGA** [SHWotever/SimHub#858]
Hola buenas tardes o dias. 
Tengo un problema intento armar iim tablero con un max7219 pero los graficos no se asemejan a la caja de cambios osea el 1 no es un nuo si no un simbolo raro el 2 3 4 5 6 etc. no se conforman en numeros si no que salen nuneros extraños. que solucion puede haber a este caso. 

desde ya muchas graicas.

**Comment by SHWotever** [comment]
Hi ! Are you sure you are using the correct kind of device in the sketch setup ? There are two kind of max7219, 7 segment or matrix. If you use the incorrect kind of display if will lead to incorrect display. If you are using the correct kind of device the issue is often linked to weak/wrong soldering, make sure that every connection are sturdy and correct.

Best regards,
Nicolas

**Comment by DAPULGA** [comment]
hola les envio la foto al parecer seria el mismo capaz difiere en algo pero ahi ya no lo se. 
lo raro que no muestra los numeros hay alguna forma en caso de diferir poder hacerlo funcionar o si o si solo resta comprar el que lleva. 
![2021-06-28 16 30 21](https://user-images.githubusercontent.com/37483256/123693252-37ba8d00-d82e-11eb-8a0e-54dc03fc8c8c.jpg)
![2021-06-28 16 30 09](https://user-images.githubusercontent.com/37483256/123693280-3c7f4100-d82e-11eb-8d72-a9a000b5e86d.jpg)

**Comment by SHWotever** [comment]
Hi ! This looks the correct module, could you double check that the pins are in correct order compared to the sketch setup ?
