### ISSUE TITLE
TrackID's now Track length rounded to 4 decimals?

### ISSUE THREAD

**Issue by Shaftoe62** [SHWotever/SimHub#865]
I just upgraded to Simhub 7.4.2. As it seems the track ID's are now the track lengths rounded to 4 decimals?

Why not the full precision of the length?

**Comment by SHWotever** [comment]
Hi ! I took a full look at al the games concerned, 3 decimals were enough to make them distinct (except the famous 2 stages we know too well) after a bit of thinking the unit are meters which means with 4 digits it's 0.1mm precision which is far enough in my mind to cover any cases. I took this opportunity to use fixed 4 digits instead of variable, which makes it easier to visualize, and generate the full list based on length when needed.

**Comment by Shaftoe62** [comment]
Ok, I was just wondering.

I had prepared for the full precision but I have everything working now.

But I also noticed that for the naming of the directories for the PersistantTracker data you did choose for the maximum precision for the car id's.

I'm renaming all the "old" directories in PlugisData to their new names so I don't loose my previous lap data. 

Which works fine by the way.

Jurgen
