### ISSUE TITLE
Full crash while playing iracing and now won't launch

### ISSUE THREAD

**Issue by beastlyfern** [SHWotever/SimHub#873]
I had simhub completely crash (had to end task) it had my bass shakers outputting constantly at almost full volume and at the same time my wheel stopped responding. Not sure why this happened but the issue I have now is that simhub will not even launch anymore, I did a full restart and still, not sure what is going on. Any help is very appreciated.  

I am using a uno board with a motor shield running to rumble motors and two server fans and I am also using sim hub for my 6 bass shakers.

[SimHub.log](https://github.com/SHWotever/SimHub/files/6820096/SimHub.log)

Thanks

**Comment by beastlyfern** [comment]
I uninstalled and reinstalled sim hub and now it will launch again. I did have to re program the uno with simhub as it was not being detected anymore by simhub. If someone can still look over the log and see what the issue was that caused the crash and required reinstalling. 

Thanks

**Comment by SHWotever** [comment]
Hi ! It looks like the crash was caused by an usb issue I can see all the devices (wheel, arduino, arduino leonardo, sim pedals ...) all failing at once. I can see that simhub could not recover from that situation and that the exit did not completely worked, that's probably why simhub could not start again, (when starting simhub checks if another instance is already running and do not start another if it's the case. When you reinstalled it probably killed the "zombie" simhub process and unlocked the situation.

Concerning the fact that you had to reprogram the arduino it's more strange, did you unplugged it before programming it ? It's probably what got it working again after this huge usb crash.

**Comment by beastlyfern** [comment]
I did unplug everything, maybe I just didn't wait long enough for it to show up in sim hub, anyways it is working now. Thanks for looking over the log much appreciated, I thought this might be the issue. I had a usb mouse on this hub and it would crash and stop working taking out my main mouse as well until a hard reset. No I just use a Bluetooth as my secondary mouse but then had this huge usb crash. I think maybe I just need a new usb hub. 

Thanks again
