### ISSUE TITLE
Assetto Corsa Competizione (ACC) - Wrong SessionBestLastLapDelta

### ISSUE THREAD

**Issue by xyz4tech** [SHWotever/SimHub#890]
The value of 'SessionBestLastLapDelta' is wrong calculated with ACC. Tested with SimHub version 7.4.6

Example values:
PersistantTrackerPlugin.SessionBestLastLapDelta 2.334
DataCorePlugin.GameData.BestLapTime 00:01:35.5440000
DataCorePlugin.GameData.LastLapTime 00:02:26.4570000

**Comment by SHWotever** [comment]
Hi ! could you describe me when this happened ? I suspect you were using a replay when seeking in it,
 this value get computed once after the lap get completed (so it refers to the previous best lap if it has been improved, or the current best laptime if not improved), so you can get your actual best lap time improvement during the last lap) (otherwise it would show "0" when you are improving your time) , which is not expected. 
 
Wwhen quickly seeking in a replay this can happen as obviously simhub whon't see the history in it's proper order.

**Comment by xyz4tech** [comment]
I have done a new test with a live training session in ACC. Please find following the data of three laps in a row:

1:
PersistantTrackerPlugin.PreviousLap_00: 00:01:38.7240000
PersistantTrackerPlugin.SessionBestLastLapDelta: 1.194

DataCorePlugin.GameData.LastLapTime: 00:01:37.8840000
DataCorePlugin.GameData.BestLapTime: 00:01:37.5300000

2:
PersistantTrackerPlugin.PreviousLap_00: 00:01:37.8840000
PersistantTrackerPlugin.SessionBestLastLapDelta: 0.354

DataCorePlugin.GameData.LastLapTime: 00:01:38.1390000
DataCorePlugin.GameData.BestLapTime: 00:01:37.5300000

3:
PersistantTrackerPlugin.PreviousLap_00: 00:01:38.1390000
PersistantTrackerPlugin.SessionBestLastLapDelta: 0.609

DataCorePlugin.GameData.LastLapTime: 00:01:37.4310000
DataCorePlugin.GameData.BestLapTime: 00:01:37.4310000

It seems the Persistant Tracker Plugin is one lap behind.

**Comment by xyz4tech** [comment]
also noticed an issue with the sector times, maybe another issue ticket

DataCorePlugin.GameData.LastLapTime: 00:01:37.4310000
DataCorePlugin.GameData.BestLapTime: 00:01:37.4310000

DataCorePlugin.GameData.Sector1BestLapTime: 00:00:32.5020000
DataCorePlugin.GameData.Sector1LastLapTime: 00:00:31.8570000

DataCorePlugin.GameData.Sector2BestLapTime: 00:00:38.5770000
DataCorePlugin.GameData.Sector2LastLapTime: 00:00:33.5730000

DataCorePlugin.GameData.Sector3BestLapTime: 00:00:33.6870000
DataCorePlugin.GameData.Sector3LastLapTime: 00:00:32.7090000

**Comment by SHWotever** [comment]
Thnaks I found it, actually lap time was provided a very short time after the lap counter and laptime was reset and I was catching it a bit too early, when observing it it was slowing down it enough to get the correct infos (Beautiful example of the Schrödinger cat :D)

I fixed it, 
concerning the sector 3 since it was deduced from the laptime (which was wrong) it is fixed at the same time ;)

**Comment by SHWotever** [comment]
Hello ! The fix is available in the last verison ! 

Have fun !
