### ISSUE TITLE
Possible Proton Support for simracing in Linux. 

### ISSUE THREAD

**Issue by requestedeverywhere** [SHWotever/SimHub#906]
Proton has come quite a long way in the time since steam started pushing it. and while I am aware, that porting the software to linux as a whole would require rewrites and a ton of effort to get the telemetry working, almost all the supported games work either out of the box or with minor modifications in linux thanks to proton, and all the major steering wheels have driver / FFB support as well. So my question is (mods tag this as a feature req plz) can we get support for simhub in either WINE, Lutris, or Proton ? All of them are forked from WINE itself and use it as a dependency, it should be possible to get telemetry from a game thats in the same prefix that you are running simhub from, lutris for instance supports running other programs on the side. so it should be possible to pass an install to a proton prefix and add simhub right to an installed game on steam.

**Comment by SHWotever** [comment]
Hi ! I'm afraid this is totally out of my reach, since i'm alone behind the scene trying to add Linux compatibility would make the release cycle too complex and too heavy (test everything twice with windows and linux and deal with each platform specificities), not counting my linux knowledge which is basically at zero level :(

**Comment by requestedeverywhere** [comment]
i get it man, its a tough ask. i may play around with the present release and see what errors it throws on attempting to run it in WINE (my linux knowledge isnt at god level but i know my way around) if it ends up running i will keep you posted.

**Comment by SkylightXD** [comment]
Hello together, 
are there any news or try to get SimHub running in Linux? :)

**Comment by depressobbq** [comment]
last time I spoke to the dev he indicated this wasnt a priority. in the
time since i've done some research on my own. SimHub itself is all of a few
libraries away from being able to "run" in proton, but thats only half the
problem. the other half is the telemetry data alot of these games hook into
apis that dont exist in linux. (some dont) and its real hit or miss as to
if you can even get the telemetry out of the game correctly.  then the
serial subsystem of linux (how you control your "gauges") is a totally
different animal to windows, that while i'm not a dev on this myself i'd
have to wager a guess would require extensive re-writes to major parts of
the code. on top of all this there's the force feedback. not all wheels FFB
is operational in *nix yet. things like the DD and the Moza come to mind.
as much as id love to abandon windows in my sim rig... its just not ready
yet my friend.

side note this isnt the only hobby that this issue crops up on. VPin
machines suffer the same issues. you can't get the fancy physical bits to
talk in linux even if you can get the "game" running.

**Comment by alkaris2** [comment]
@depressobbq Many Linux embedded devices have their own specifics for interacting with hardware with haptics and sensor devices that are controlled with an API, code for haptics obviously is one that already exists for many Linux devices, especially when they can handle hardware devices for Braille which relies on such feedback for certain things. While not a job for one person to manage and test on their own, or to code from scratch, but the code base for it can be adapted for more than just Braille.

Euro Truck Simulator 2 for example has both native versions for Windows and Linux, and modding the game with extended functionality passed to real hardware would be relatively simple too since it uses FMOD. Many games that utilize FMOD when allowing mods to be made for the game. If SimHub uses FMOD porting code wouldn't be necessary for other platforms, since the game would just use and read the FMOD scripts.

**Comment by depressobbq** [comment]
thats a pretty big IF, now while you arent wrong and I can think of a few
games that use fmod. not all do the ones that dont arent going to suddenly
switch for us linux nerds.  and then there is the other stuff simhub does.
each one will require different levels of F around and find out to get
working right.  things like addressing serial devices for example are
totally different from windows to linux. the sound subsystems used to
generate vibrations in the bass shakers is another I can think of that
wouldnt be as easy as just making it work in proton. I suppose all this
could be sorted out in the future, but we gotta remember our place here. we
are linux users that are the 2% of PC gamers, and of that 2% theres what
maybe 20 of us floating around interested in simming on linux? Id love to
see it happen, but dude already told me flat it wasnt a priority. im
surprised the issues not closed up on us already.

**Comment by spikerguy** [comment]
Hello everyone here, 

For those looking for simhub on Linux. 

A developer have worked his way into similar software for linux. 

https://github.com/Spacefreak18/monocoque

Please check it out. 

I have made some videos after testing some diy rumble pedals as well as cammus c5 rpm leds and lcd . 


Also checkout some videos I made

https://youtube.com/shorts/TznEHQ4lPZM

You're all welcome to join the developer and testing at monocoque project. 

Simhub was the inspiration for the Linux project. 


https://youtube.com/shorts/t27kFte_fIE


https://youtu.be/AsGykUZkEl0

Sorry for the shameless video plug but we're trying to get more testers and users for this project. 


You can also join our chat on matrix

#simracer:matrix.org

Cheers
