### ISSUE TITLE
Paying for the license with paypal

### ISSUE THREAD

**Issue by Kingzzz65** [SHWotever/SimHub#907]
I've payed 5 euro for the license but I didn't get it. How can I get it now?

**Comment by SHWotever** [comment]
Hi ! Usually this happens when you still have an old email linked to your PayPal PayPal account, do not hesitate to send your payment details (PayPal email and PayPal transaction Id) here on the contact  form so I can send you a copy : https://www.simhubdash.com/simhub-contact/

Best regards,
Nicolas

**Comment by Kingzzz65** [comment]
Thanks Nicolas I got it now

**Comment by SHWotever** [comment]
Perfect, have fun !
