### ISSUE TITLE
Shakeit motor issue

### ISSUE THREAD

**Issue by Rukibb** [SHWotever/SimHub#934]
shakit motors sometimes reboot themselves.
[SimHub.log](https://github.com/SHWotever/SimHub/files/7262079/SimHub.log)

**Comment by SHWotever** [comment]
Hi !

From the log I can see that the Arduino stops responding and that simhub automatically restarts the connection . This is likely to be parasites related Arduino freezes, you can find general advices about how to solve those issues here : https://github.com/SHWotever/SimHub/wiki/Arduino-Shake-It#about-parasites

Nicolas

**Comment by Rukibb** [comment]
Thanks for your quick reply. I have 2 individual uno boards setup for 2 wind simulators named 1 & 2.
They always reboot at the same time, i don't know wheather it is a hardware or software issue. While rebooting, there was no usb reconnect sound. Those two wind simulators are recognized properly. The fans stop, and restart in few seconds. Individual 2A power supply is using in each board to power two 0.93A fans, which are set 30% power static wind. I think the power supply is enough.  Anyway i will try the solutions listed in the link first.

**Comment by SHWotever** [comment]
Hi ! Indeed the usb disconnect won't happen all the time, arduino is splitted in two components, the usb to tll chip, and the arduino chip itself, in this case it seems that it's the arduino chip which got frozen or stuck. 

In the log it's the arduino "Wind simulator 2" which got stuck twice (when this happen, simhub will try to force resync and will suspend other operations until it catches up, that's why you feel that both are stopping, But in reality it's only the "Wind simulator 2" which is having issues.

**Comment by Rukibb** [comment]
Now i will forus on the hardware on wind simulator 2. Thanks for analysis the log file. Thanks all the simhub team
