### ISSUE TITLE
SimHub freezes

### ISSUE THREAD

**Issue by andreasdahl1987** [SHWotever/SimHub#952]
I've had this freeze issue for a while. Every 5 minutes or so, simhub freezes for a few seconds. My log files were so messy because of badly coded plugin and scripts + dashboard, but I've now cleaned things up and discovered this in the log. Same thing repeating many times, it also started a new log file without me exiting simhub, not sure if that is intended. What could the problem be?

[SimHub.log](https://github.com/SHWotever/SimHub/files/7500190/SimHub.log)

**Comment by SHWotever** [comment]
Hi ! Indeed the log file is splitted automatically every 3mb approximately. Would you have the first log files ? I've already seen such error but often it's a consequence and the cause is available at the beginning of the log.

**Comment by andreasdahl1987** [comment]
Ok, I was able to capture it nicely. At at 19:53 is when it froze for about 5 sec. Forced arduino sync?

[SimHub.log](https://github.com/SHWotever/SimHub/files/7515251/SimHub.log)

**Comment by andreasdahl1987** [comment]
Seems like it is related to my wind sim? Can you tell what the issue might be?

**Comment by SHWotever** [comment]
Hi indeed this stack shows an anomaly with the wind sim, in this case, simhub will lock until it catches up or if it takes too long disconnect restart the arduino and try again. In this case it's the second one which happens (timeout) i would check for cable, parasites etc, maybe power source. Since the arduino does not totally disconnect it's more something about power or parasites affecting the main arduino chip (the usb chip is still alive apparently)

**Comment by andreasdahl1987** [comment]
Cheers, I'll have a look at it :)
