### ISSUE TITLE
Sim Racing Newbie....how to use Sim Commander and SimHub at the same time?

### ISSUE THREAD

**Issue by jrock2403** [SHWotever/SimHub#963]
I have an Accuforce V2 wheel, a ButtKicker Gamer 2, SSH Shifter, Clubsport Pedals V3. I am planning to use SimCommander for the wheel settings and SimHub for the Buttkicker settings (I tried SC for both settings and found clipping and shutting down the BKG2 amp much more likely). So my questions are....

1. How do I ensure for games like iRacing or F1, I am loading settings from both programs, given you have to open a game through one of them initially? I know this might be obvious but I'm clueless as new to sim racing.

2. Any recommendations on SimHub settings for the BKG2? It seems like Simhub is better in general for tweaking, but SC was much better in terms of feel "out of the box." 

Thanks!

**Comment by SHWotever** [comment]
Hi ! You can run both software at the same time, simhub does not require to start the game through simhub, as long as telemetry is enabled in game it can be launched the way you want. However for games like F1 games where telemetry technology can't be sahred you have some advanced configuration to do in order to share data to both sofwares :
https://github.com/SHWotever/SimHub/wiki/Sharing-UDP-data-with-other-applications

Concerning tuing you have an introduction here : https://github.com/SHWotever/SimHub/wiki/ShakeIt-V3-Effects-configuration

**Comment by jrock2403** [comment]
Thanks, I appreciate the help

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
