### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by damiank388** [SHWotever/SimHub#965]
**Is your feature request related to a problem? Please describe.**
Dash Studio - Cycle next/prev dash template/screen - do not work with VoCore displays, but it works for overlays  

**Describe the solution you'd like**
Per VoCore display- key binding - to cycle screen ( pages) is more requested rather than templates

**Comment by SHWotever** [comment]
Hi there was a bug when changing the game which has been fixed with the latest beta : https://www.simhubdash.com/unofficial/SimHub.7.04.12b6.zip could you test it ? I've not seen any additional issues with this feature.

Take care of template change, if you get "only favouites" checked this will lock to only favourites, if you have some.

Concerning screen change make sure to test when in race, screen have roles, and it will only scroll through the available pages for the current role.

**Comment by damiank388** [comment]
Hi,
I'm on latest beta. 
Cycle only through favourites - not checked. 
For both template and screen 2 keys assigned - Fanatec Wheel - Button Box

Dash template used -Bosch DDU8 - comes with simhub, has all pages accessible both in game and idle

2x VoCore connected 
1x Overlay 

In game, during race - ACC

Cycles dash templates - cycles overlays - nothing happens on either vocore
Show next dash screen- nothing happens

**Comment by damiank388** [comment]
How would that even supposed to work with one button and 2 vocores connected? 
Would it cycle pages on both ?

**Comment by SHWotever** [comment]
Hi took a seconf look and everything went fine. I even tried to use the same control for both screens and it made both changes without issues.

Are you using the screen dedicated controls ? 
![image](https://user-images.githubusercontent.com/2207331/142724859-6bd8128c-3aea-4d6f-818a-837085ccd376.png)

If not that would explain it. Each screen has it's own set of controls.

If it's not that could you try again with the debug mode enabled and send me the log ? 
![image](https://user-images.githubusercontent.com/2207331/142724892-2539a03a-3e4b-405f-ae1e-816ac737b0c3.png)

**Comment by damiank388** [comment]
I'm an idiot... That explains it all xD
