### ISSUE TITLE
VoCore not connecting correctly 

### ISSUE THREAD

**Issue by damiank388** [SHWotever/SimHub#975]
*Describe the bug*
5'' VoCore is not not connecting to simhub if multiple other devices are connected via USB hub (including full motion rig)

VoCore is connected directly to PC.
It identifies itself correctly as USB2.0 Screen in device manager.
All other devices are connected via a powered industrial hub.
SimHUB can't establish connection.

1. PC has to be rebooted with HUB unplugged.
2. VoCore connected directly to PC then connects correctly. 
3. Connecting usb hub after connection is established, does not break the connection. 

*Simhub version*
7.04.12 /   VoCore PCB v7b/ SimHUB recommended drivers installed

USB hub 
https://www.startech.com/en-us/cards-adapters/hb30a10ame?fbclid=IwAR0kg76qNsZ0fnjf-PMQTjhRQEFJfcuf_DMnotbuRiMPDqPIFfsyXXE_7D8

**Comment by loganross2001** [comment]
In terms of what is connected to that hub, it is the following:
Logitech trackball
Dbox gen 3 4250i
Motionhouse wind simulator
Huesinkveld pedals and handbrake
Fanatec dd2. 

Connected directly to the Asus z690 MB USB ports are a Logitech keyboard adapter and the VoCore based dash.

**Comment by loganross2001** [comment]
This is the USB (but the VoCore is connected directly to the pc, not through the hub.

https://www.startech.com/en-us/cards-adapters/hb30a10ame

**Comment by SHWotever** [comment]
Hi ! That looks like some usb conflicts, I'm not sure something can be done on simhub side. 
Could you also make sure you are using an usb 2 port for the screen ? Vocore is known that have some issues with usb 3.
Can you tell me which driver you are using ? The manufacturer driver (vocore) or the simhub one ?

Could you join the simhub log files after it happens to check if simhub can even see the screen ?

**Comment by loganross2001** [comment]
Unfortunately this PC has no usb 2 ports.  Asus Maximus z690 motherboard.  Tried both, but if you link to Simhub Version, I will try again.  I will also try a usb 2.0  hub as a middleman.

Sent from my iPad

On Nov 26, 2021, at 10:30 PM, Wotever ***@***.***> wrote:

﻿

Hi ! That looks like some usb conflicts, I'm not sure something can be done on simhub side.
Could you also make sure you are using an usb 2 port for the screen ? Vocore is known that have some issues with usb 3.
Can you tell me which driver you are using ? The manufacturer driver (vocore) or the simhub one ?

Could you join the simhub log files after it happens to check if simhub can even see the screen ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSHWotever%2FSimHub%2Fissues%2F975%23issuecomment-980511395&data=04%7C01%7C%7C43c1f95283ae48673a7c08d9b16f5580%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735914010505161%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p5O72A4ZDJwTLfYS8DO%2FxkdMeUuXmI9vvSKmSuej3yc%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHBDYEGEJTO5UQI2I3CIN7LUOB3GLANCNFSM5I3RGJSA&data=04%7C01%7C%7C43c1f95283ae48673a7c08d9b16f5580%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735914010515149%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2zjuHSQsGguHiARjGT0NHjnHGaS8JMV4%2FrWyrYIQhao%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C43c1f95283ae48673a7c08d9b16f5580%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735914010525145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FyFXUcH19YaDLlKHsB2DRWrF1ERBTp1kBSzvL27a9BY%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C43c1f95283ae48673a7c08d9b16f5580%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735914010525145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=K6GHBCJMXL4w1BtmMxY4NzB6qnEblMiXblHhDfjVo4g%3D&reserved=0>.

**Comment by SHWotever** [comment]
Hi ! You can find all the informations here : https://github.com/SHWotever/SimHub/wiki/Dashstudio---USB-Displays#wiring

**Comment by SHWotever** [comment]
It would be interesting to also test the manufacturer provided sample after restarting the computer. If the sample can't work neither that would allow to know if the issue is in simhub or in the screen firmware itself.

**Comment by loganross2001** [comment]
I may have discovered the conflict.  The issue seems to be a conflict with the motionhouse wind system. I will check with them.

Sent from my iPhone

On Nov 26, 2021, at 11:38 PM, Wotever ***@***.***> wrote:

﻿

It would be interesting to also test the manufacturer provided sample after restarting the computer. If the sample can't work neither that would allow to know if the issue is in simhub or in the screen firmware itself.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSHWotever%2FSimHub%2Fissues%2F975%23issuecomment-980519290&data=04%7C01%7C%7C5c58879f4fc6444b127a08d9b178d8ec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735954863027588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vAQ6A2cICRD2Nu%2B9qAGWR21KkPjAK3d0Tvnu7ljtalc%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHBDYEEMDUPHGLZD3O6FWBLUOCDFXANCNFSM5I3RGJSA&data=04%7C01%7C%7C5c58879f4fc6444b127a08d9b178d8ec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735954863037580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hvkGMSz4Avw3uZg9xqwzJlcKeUqQ%2BnHHlZqGUp%2FfBQI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C5c58879f4fc6444b127a08d9b178d8ec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735954863037580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gj1ueW74Jikcx9Tf1XnJfc0V1BL8a33kTkorir4IFwE%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C5c58879f4fc6444b127a08d9b178d8ec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637735954863047581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3j5racYDRadWCJVsfRkJmBCfQjYN%2BCAKTe1u70gHKEM%3D&reserved=0>.

**Comment by SHWotever** [comment]
Hi ! Thanks for the feedback !
